<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="aurora-v2">
<div class="au-aurora-bg" aria-hidden="true"></div><div class="au-content-wrap landing-feed">
<?php if (($view['site']['skin_presentation']['options']['au_profile_header'] ?? '') === '1'): ?><section class="au-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="au-profile-avatar au-profile-avatar--zoom"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="Profile avatar"></div><?php else: ?><div class="au-profile-avatar"><span class="au-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div><?php endif; ?>
<div class="au-profile-info"><div class="au-profile-nameline"><h1 class="au-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['au_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="au-profile-tagline-sep">/</span><p class="au-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div>
<div class="au-profile-stats"><div class="au-profile-stat"><span class="au-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="au-profile-stat-label">posts</span></div></div><?php if (!empty($view['site']['site_description'])): ?><p class="au-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></section><?php endif; ?>
<nav class="au-sticky-nav" aria-label="Site navigation"><div class="au-sticky-nav-inner"><ul class="au-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag'): ?><main><div id="browse-grid" class="au-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="au-tile"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post'): ?><main><article class="au-post-ig"><div class="au-post-ig-image"><?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'au-single-img'])); ?><?php endif; ?></div><div class="au-post-ig-info"><div class="au-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="au-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="au-static-page"><h1 class="au-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="au-static-content"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></article></main>
<?php else: ?><main><section class="au-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer"><div id="footer"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
