<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<?php
/**
 * SNAPSMACK_EOF_HEADER
 *     <?php // ===== SNAPSMACK EOF =====
 * Last non-empty line of this file MUST match the line above.
 * Missing or different = truncated/corrupted. Restore before saving.
 */
?>
<?php if (!empty($view['response']['fragment']) && ($view['response']['kind'] ?? '') === 'photo'): ?>
<article class="go-post-ig">
<div class="go-post-ig-image"><?php if (!empty($view['response']['item']['img_file'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'go-single-img'])); ?><?php endif; ?></div>
<div class="go-post-ig-info">
<div class="go-post-ig-header"><button class="go-back-btn" type="button" aria-label="Back to grid">&#8592;</button><?php if (!empty($view['site']['avatar_url'])): ?><img class="go-post-ig-avatar" src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt=""><?php else: ?><span class="go-post-ig-avatar go-post-ig-avatar--initials">S</span><?php endif; ?><span class="go-post-ig-sitename"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div>
<div class="go-post-ig-body">
<div class="go-post-caption-block"><p class="go-post-ig-caption"><span class="go-post-ig-caption-user"><?php echo snap_escape_html($view['site']['site_name']); ?></span><?php if (!empty($view['response']['item']['img_title'])): ?> <?php echo snap_escape_html($view['response']['item']['img_title']); ?><?php endif; ?><?php if (!empty($view['response']['item']['content']) || !empty($view['response']['item']['description']) || !empty($view['response']['item']['img_description'])): ?><br><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description']); ?><?php endif; ?></p></div>
<?php if (!empty($view['response']['item']['exif'])): ?><div id="go-exif-panel" class="go-exif-panel"><?php foreach (['camera' => 'Camera', 'lens' => 'Lens', 'focal' => 'Focal', 'film' => 'Film', 'iso' => 'ISO', 'aperture' => 'Aperture', 'shutter' => 'Shutter', 'flash' => 'Flash'] as $key => $label): ?><?php if (!empty($view['response']['item']['exif'][$key])): ?><div class="go-exif-item" data-exif-key="<?php echo snap_escape_attr($key); ?>"><span class="go-exif-label"><?php echo snap_escape_html($label); ?></span><span class="go-exif-value"><?php echo snap_escape_html($view['response']['item']['exif'][$key]); ?></span></div><?php endif; ?><?php endforeach; ?></div><?php endif; ?>
<div class="go-community-wrap"><?php if (!empty($view['response']['comments'])): ?><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments']])); ?><?php endif; ?><button class="go-play-as-puzzle" type="button" data-play-as-puzzle data-thumb="<?php echo snap_escape_url($view['response']['item']['img_thumb_square'] ?? $view['response']['item']['img_file'] ?? ''); ?>" data-full="<?php echo snap_escape_url($view['response']['item']['img_file'] ?? ''); ?>" data-post-url="<?php echo snap_route_url('photo', ['slug' => $view['response']['item']['img_slug'] ?? '']); ?>" data-label="<?php echo snap_escape_attr($view['response']['item']['img_title'] ?? 'Photograph'); ?>" data-focus-x="<?php echo snap_escape_attr($view['response']['item']['img_focus_x'] ?? ''); ?>" data-focus-y="<?php echo snap_escape_attr($view['response']['item']['img_focus_y'] ?? ''); ?>" data-zoom="<?php echo snap_escape_attr($view['response']['item']['img_zoom'] ?? ''); ?>">PLAY AS PUZZLE</button></div>
</div>
<div class="go-post-ig-actions"><div class="go-post-ig-action-icons"><button type="button" class="go-action-btn" aria-label="Comment" data-ss-action="scroll-to" data-ss-target=".go-community-wrap"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg></button><button type="button" class="go-action-btn go-action-bookmark" aria-label="Save"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg></button></div><?php if (!empty($view['response']['item']['created_at'])): ?><p class="go-post-ig-date"><?php echo snap_escape_html($view['response']['item']['created_at']); ?></p><?php endif; ?></div>
</div>
</article>
<?php else: ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="game-on-v2<?php if (($view['response']['kind'] ?? '') === 'blogroll'): ?> is-blogroll<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?> is-static-page<?php endif; ?>" data-carousel-indicator="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['carousel_indicator'] ?? ''); ?>" data-hover-overlay="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['hover_overlay'] ?? ''); ?>">
<?php if (($view['response']['kind'] ?? '') === 'photo'): ?><div id="snap-nav-data" hidden data-prev="<?php echo snap_escape_url($view['response']['previous']['url'] ?? ''); ?>" data-next="<?php echo snap_escape_url($view['response']['next']['url'] ?? ''); ?>" data-first="<?php echo snap_escape_url($view['response']['first']['url'] ?? ''); ?>" data-last="<?php echo snap_escape_url($view['response']['last']['url'] ?? ''); ?>"></div><?php endif; ?>
<div class="go-puzzle-field" data-game-on data-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_puzzle_mode']); ?>" data-palette="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_border_palette']); ?>" data-direction="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_border_direction']); ?>" data-puzzle-density="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_puzzle_density']); ?>" data-activity="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_motion_activity']); ?>" data-speed="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_motion_speed']); ?>" data-border-activity="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_border_activity']); ?>" data-modal-theme="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['go_modal_theme']); ?>" data-score-url="<?php echo snap_route_url('game-scores'); ?>" data-help-url="<?php echo snap_route_url('page', ['slug' => 'how-to-play-15-puzzle']); ?>">
<?php foreach (($view['response']['puzzle_items'] ?? $view['response']['items'] ?? []) as $index => $item): ?><?php if (!empty($item['img_thumb_square']) || !empty($item['img_thumb_aspect']) || !empty($item['img_file'])): ?><button class="go-puzzle" type="button" data-puzzle-index="<?php echo snap_escape_attr($index); ?>" data-thumb="<?php echo snap_escape_url($item['img_thumb_square'] ?? $item['img_thumb_aspect'] ?? $item['img_file']); ?>" data-full="<?php echo snap_escape_url($item['img_file'] ?? $item['img_thumb_square'] ?? ''); ?>" data-post-url="<?php echo snap_route_url('photo', ['slug' => $item['post_img_slug'] ?? $item['img_slug'] ?? '']); ?>" data-label="<?php echo snap_escape_attr($item['post_title'] ?? $item['img_title'] ?? 'Photograph'); ?>" data-focus-x="<?php echo snap_escape_attr($item['img_focus_x'] ?? ''); ?>" data-focus-y="<?php echo snap_escape_attr($item['img_focus_y'] ?? ''); ?>" data-zoom="<?php echo snap_escape_attr($item['img_zoom'] ?? ''); ?>"></button><?php endif; ?><?php endforeach; ?>
<div class="go-puzzle-tone" aria-hidden="true"></div><div class="go-puzzle-edge-mask" aria-hidden="true"></div></div>
<div class="go-content-wrap landing-feed">
<?php if (($view['site']['skin_presentation']['options']['go_profile_header'] ?? '') === '1'): ?><section class="go-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="go-profile-avatar go-profile-avatar--zoom"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="Profile avatar"></div><?php else: ?><div class="go-profile-avatar"><span class="go-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div><?php endif; ?>
<div class="go-profile-info"><div class="go-profile-nameline"><h1 class="go-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['go_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="go-profile-tagline-sep">/</span><p class="go-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div>
<div class="go-profile-stats"><div class="go-profile-stat"><span class="go-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="go-profile-stat-label">posts</span></div></div><?php if (!empty($view['site']['site_description'])): ?><p class="go-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></section><?php endif; ?>
<nav class="go-sticky-nav" aria-label="Site navigation"><div class="go-sticky-nav-inner"><ul class="go-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag'): ?><main><div id="browse-grid" class="go-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="go-tile<?php if (!empty($item['is_framed'])): ?> go-tile--framed<?php endif; ?>" style="<?php echo snap_escape_attr($item['frame_style'] ?? ''); ?>"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo'): ?><main><div id="browse-grid" class="go-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="go-tile<?php if (!empty($item['is_framed'])): ?> go-tile--framed<?php endif; ?>" style="<?php echo snap_escape_attr($item['frame_style'] ?? ''); ?>"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'post'): ?><main><article class="go-post-ig"><div class="go-post-ig-image">
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="go-carousel-wrap"><div id="tg-carousel" class="ss-slider" data-slider-mode="carousel"><div class="slider-track"><?php foreach ($view['response']['photographs'] as $photograph): ?><div class="slider-slide<?php if (!empty($photograph['is_framed'])): ?> go-slide--framed<?php endif; ?>" data-image-id="<?php echo snap_escape_attr($photograph['id'] ?? ''); ?>" style="<?php echo snap_escape_attr($photograph['frame_style'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $photograph['img_file'] ?? '', 'alt' => $photograph['img_alt'] ?? $photograph['img_title'] ?? '', 'attributes' => ['data-lightbox-src' => $photograph['img_file'] ?? '']])); ?></div><?php endforeach; ?></div></div></div>
<?php elseif (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'go-single-img'])); ?><?php endif; ?><button class="go-play-as-puzzle" type="button" data-play-as-puzzle data-action-placement="community" data-thumb="<?php echo snap_escape_url($view['response']['item']['img_thumb_square'] ?? $view['response']['item']['img_file'] ?? ''); ?>" data-full="<?php echo snap_escape_url($view['response']['item']['img_file'] ?? ''); ?>" data-post-url="<?php echo snap_route_url('photo', ['slug' => $view['response']['item']['img_slug'] ?? '']); ?>" data-label="<?php echo snap_escape_attr($view['response']['item']['img_title'] ?? 'Photograph'); ?>" data-focus-x="<?php echo snap_escape_attr($view['response']['item']['img_focus_x'] ?? ''); ?>" data-focus-y="<?php echo snap_escape_attr($view['response']['item']['img_focus_y'] ?? ''); ?>" data-zoom="<?php echo snap_escape_attr($view['response']['item']['img_zoom'] ?? ''); ?>">Play as puzzle</button></div><div class="go-post-ig-info"><div class="go-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="go-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><main class="go-search-view"><header class="go-search-head"><h1>Search results</h1><p>Photographs for &ldquo;<?php echo snap_escape_html($view['response']['query'] ?? ''); ?>&rdquo;</p></header><?php if (!empty($view['response']['results']['photographs'])): ?><div id="browse-grid" class="go-grid public-grid h-feed archive-grid"><?php foreach (($view['response']['results']['photographs'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="go-tile"><a href="<?php echo snap_route_url('photo', ['slug' => $item['img_slug'] ?? '']); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div><?php else: ?><div class="go-search-empty">No photographs matched that search.</div><?php endif; ?></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="go-static-page"><h1 class="go-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="go-static-content"><?php if (!empty($view['response']['item']['image_asset'])): ?><figure class="go-page-hero go-page-hero--<?php echo snap_escape_attr($view['response']['item']['image_size'] ?? 'full'); ?> go-page-hero--<?php echo snap_escape_attr($view['response']['item']['image_align'] ?? 'center'); ?><?php if (!empty($view['response']['item']['image_shadow'])): ?> go-page-hero--shadow<?php endif; ?>"><img src="<?php echo snap_escape_url($view['response']['item']['image_asset']); ?>" alt="<?php echo snap_escape_attr($view['response']['item']['title'] ?? ''); ?>"></figure><?php endif; ?><div class="go-static-body"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'blogroll'): ?><main><article class="go-static-page go-blogroll"><h1 class="go-static-title"><?php echo snap_escape_html($view['response']['page_title'] ?? 'BLOGROLL'); ?></h1><div class="go-static-content blogroll-canvas"><?php foreach (($view['response']['blogroll_groups'] ?? []) as $group): ?><section class="blogroll-category-block"><h2 class="blogroll-category-heading"><?php echo snap_escape_html($group['label'] ?? ''); ?></h2><?php foreach (($group['items'] ?? []) as $peer): ?><div class="blogroll-peer"><div class="blogroll-peer-name"><a href="<?php echo snap_escape_url($peer['url'] ?? ''); ?>" target="_blank" rel="noopener noreferrer"><?php echo snap_escape_html($peer['name'] ?? ''); ?></a></div><?php if (!empty($peer['description'])): ?><p class="blogroll-peer-desc"><?php echo snap_escape_html($peer['description']); ?></p><?php endif; ?></div><?php endforeach; ?></section><?php endforeach; ?></div></article></main>
<?php else: ?><main><section class="go-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="ss-slider-dots" data-slider-indicators><?php foreach ($view['response']['photographs'] as $slideIndex => $photograph): ?><button type="button" class="ss-slider-dot<?php if ($slideIndex === 0): ?> is-active<?php endif; ?>" data-slide-index="<?php echo snap_escape_attr($slideIndex); ?>" aria-label="<?php echo snap_escape_attr($photograph['img_title'] ?? 'Photograph'); ?>"></button><?php endforeach; ?></div><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer<?php if (!empty($view['site']['footer']['lowercase'])): ?> footer-lowercase<?php endif; ?>"><div id="footer" class="inside"><?php echo snap_render_html(snap_render_component('footer', ['footer' => $view['site']['footer'] ?? []])); ?></div></footer></div>
<div id="go-modal-overlay" class="go-modal-overlay" hidden data-grid-url="<?php echo snap_route_url('home'); ?>"<?php if (!empty($view['response']['autoopen'])): ?> data-autoopen="1"<?php endif; ?>><div class="go-modal-backdrop"></div><div id="go-modal-frame" class="go-modal-frame"></div></div><div id="go-lightbox" class="go-lightbox" hidden><button type="button" class="go-lightbox-close" aria-label="Close">&times;</button><img class="go-lightbox-img" src="" alt=""></div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html><?php endif; ?>
<?php // ===== SNAPSMACK EOF =====
