<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?></head>
<body class="hip-to-be-square-v2"><header id="header" class="site-header" data-sticky-header><div class="inside"><a class="site-title logo-area" href="<?php echo snap_route_url('home'); ?>"><span class="site-title-text"><?php echo snap_escape_html($view['site']['site_name']); ?></span></a><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></div></header>
<main id="scroll-stage" class="public-content">
<?php if (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post' || ($view['response']['kind'] ?? '') === 'page' || ($view['response']['kind'] ?? '') === 'collection'): ?>
<article id="photobox" class="h-entry single-image-page"><h1 class="p-name photo-title-footer"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? $view['response']['item']['name'] ?? ''); ?></h1><?php if (!empty($view['response']['item']['img_date']) || !empty($view['response']['item']['created_at'])): ?><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?>"><?php echo snap_escape_html($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?></time><?php endif; ?><?php if (!empty($view['site']['owner_name'])): ?><span class="p-author h-card"><span class="p-name"><?php echo snap_escape_html($view['site']['owner_name']); ?></span></span><?php endif; ?>
<?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><div class="htbs-gallery-room"><div class="frame-mount" data-bevel="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['htbs_bevel_style'] ?? ''); ?>" data-wood-grain="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['htbs_wood_grain'] ?? ''); ?>"><div class="frame-border"><div class="frame-mat"><div class="frame-bevel"><div class="frame-image u-photo post-image-wrap"><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'post-image'])); ?></div></div></div></div></div></div><?php endif; ?>
<div id="infobox" class="entry-content e-content static-transmission"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></article>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><section class="search-results"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? 'Search'); ?></h1><?php foreach (($view['response']['results'] ?? []) as $group): ?><?php foreach ($group as $item): ?><article><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? ''); ?></h2></article><?php endforeach; ?><?php endforeach; ?></section>
<?php elseif (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'albums' || ($view['response']['kind'] ?? '') === 'collections'): ?><section id="browse-grid" class="public-grid h-feed archive-grid"><?php foreach (($view['response']['items'] ?? []) as $item): ?><article><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>"><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? $item['name'] ?? ''); ?></h2></a></article><?php endforeach; ?></section>
<?php else: ?><section class="not-found"><h1>Not found</h1></section><?php endif; ?>
<?php if (!empty($view['response']['comments'])): ?><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments']])); ?><?php endif; ?></main>
<footer id="system-footer" class="site-footer"><div id="footer" class="inside"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer><?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>

