<?php
/**
 * SNAPSMACK - Style override manager.
 * Orchestrates custom CSS injections for public and administrative interfaces.
 * Uses forced inline styling to maintain a terminal-themed editor interface.
 * Git Version Official Alpha 0.5
 */

require_once 'core/auth.php';

// --- 1. TARGET ROUTING ---
// Determine whether the user is modifying public frontend or admin dashboard styles.
$target = $_GET['v'] ?? 'public'; 
$db_key = ($target === 'admin') ? 'custom_css_admin' : 'custom_css_public';

// --- 2. SAVE LOGIC ---
if (isset($_POST['save_overrides'])) {
    $manual_content = $_POST['manual_overrides'];
    $protected_skin_content = $_POST['skin_css_buffer']; 
    
    // Combine the read-only skin block with the user-defined overrides.
    $final_blob = trim($protected_skin_content . "\n\n" . $manual_content);
    
    $check = $pdo->prepare("SELECT COUNT(*) FROM snap_settings WHERE setting_key = ?");
    $check->execute([$db_key]);
    
    // Perform an upsert to save the combined CSS blob.
    if ($check->fetchColumn() > 0) {
        $stmt = $pdo->prepare("UPDATE snap_settings SET setting_val = ? WHERE setting_key = ?");
    } else {
        $stmt = $pdo->prepare("INSERT INTO snap_settings (setting_val, setting_key) VALUES (?, ?)");
    }

    if ($stmt->execute([$final_blob, $db_key])) {
        // Redirect back to the manager view.
        header("Location: smack-css.php?v=" . $target . "&msg=CALIBRATED");
        exit;
    }
}

// --- 3. READ & SPLIT LOGIC ---
// Retrieves raw data and isolates the skin-generated block via comment tags.
$stmt = $pdo->prepare("SELECT setting_val FROM snap_settings WHERE setting_key = ?");
$stmt->execute([$db_key]);
$raw_data = $stmt->fetchColumn() ?: "";

$pattern = '/\/\* SKIN_START \*\/.*?\/\* SKIN_END \*\//s';
$skin_block = "";
$user_block = $raw_data;

if (preg_match($pattern, $raw_data, $matches)) {
    $skin_block = $matches[0];
    $user_block = trim(str_replace($skin_block, '', $raw_data));
}

$page_title = "STYLE OVERRIDES";
include 'core/admin-header.php';
include 'core/sidebar.php';
?>

<div class="main">

    <div class="header-row">
        <h2>STYLE OVERRIDES: <?php echo strtoupper($target); ?></h2>
        
        <div class="view-selector-wrap">
            <select onchange="window.location.href='smack-css.php?v=' + this.value">
                <option value="public" <?php if ($target === 'public') { echo 'selected'; } ?>>PUBLIC SITE OVERRIDES</option>
                <option value="admin" <?php if ($target === 'admin') { echo 'selected'; } ?>>ADMIN PANEL OVERRIDES</option>
            </select>
        </div>
    </div>

    <?php if (isset($_GET['msg'])): ?>
        <div class="alert box alert-success">> ARCHITECTURE CALIBRATED</div>
    <?php endif; ?>

    <form method="POST">
        
        <?php if ($skin_block): ?>
        <div class="box">
            <div class="lens-input-wrapper">
                <label>GENERATED BY SKIN ADMIN (READ ONLY)</label>
                <textarea name="skin_css_buffer" readonly spellcheck="false" 
                          style="height: 300px !important; font-family: 'Courier Prime', 'Courier New', monospace !important; font-size: 0.75rem !important; line-height: 1.4 !important; color: #777777 !important; background: transparent !important; border: 1px solid rgba(255, 255, 255, 0.1) !important; width: 100% !important; display: block !important; padding: 15px !important; resize: none !important;"><?php echo htmlspecialchars($skin_block); ?></textarea>
            </div>
        </div>
        <?php else: ?>
            <input type="hidden" name="skin_css_buffer" value="">
        <?php endif; ?>

        <div class="box">
            <div class="lens-input-wrapper">
                <label>MANUAL OVERRIDES</label>
                <small style="display: block !important; margin-bottom: 10px !important; color: rgba(255, 255, 255, 0.4) !important; font-family: 'Courier Prime', monospace !important; font-size: 0.8rem !important;">/* These styles are injected after the main stylesheet. Safe to edit. */</small>
                
                <textarea name="manual_overrides" spellcheck="false"
                          style="height: 400px !important; font-family: 'Courier Prime', 'Courier New', monospace !important; font-size: 0.95rem !important; background-color: #000000 !important; color: #e0e0e0 !important; border: 1px solid rgba(255, 255, 255, 0.2) !important; width: 100% !important; display: block !important; padding: 20px !important; resize: vertical !important;"><?php echo htmlspecialchars($user_block); ?></textarea>
            </div>
            
            <button type="submit" name="save_overrides" class="master-update-btn" 
                    style="margin-top: 30px !important; padding: 0 30px !important; height: 52px !important; width: 100% !important; display: flex !important; align-items: center !important; justify-content: center !important;">
                SAVE <?php echo strtoupper($target); ?> OVERRIDES
            </button>
        </div>
        
    </form>
    
</div>

<?php include 'core/admin-footer.php'; ?>