<?php
/**
 * SNAPSMACK - Style Override Manager
 * Version: 16.55 - Zero Inline Styles
 * -------------------------------------------------------------------------
 * - All styles live in geometry + colours CSS files (section 26 / 17).
 * - Uses .header-row--ruled for the underlined header with actions.
 * - Uses .css-tab / .css-tab-active for view switcher buttons.
 * - Uses .css-preview-block for read-only skin CSS display.
 * - Uses .css-override-textarea for the manual editor.
 * -------------------------------------------------------------------------
 */

require_once 'core/auth.php';

// --- 1. TARGET ROUTING ---
$target = $_GET['v'] ?? 'public';
$db_key = ($target === 'admin') ? 'custom_css_admin' : 'custom_css_public';

// --- 2. SAVE LOGIC ---
if (isset($_POST['save_overrides'])) {

    $manual_content        = $_POST['manual_overrides'];
    $protected_skin_content = $_POST['skin_css_buffer'];

    $final_blob = trim($protected_skin_content . "\n\n" . $manual_content);

    $check = $pdo->prepare("SELECT COUNT(*) FROM snap_settings WHERE setting_key = ?");
    $check->execute([$db_key]);

    if ($check->fetchColumn() > 0) {
        $stmt = $pdo->prepare("UPDATE snap_settings SET setting_val = ? WHERE setting_key = ?");
    } else {
        $stmt = $pdo->prepare("INSERT INTO snap_settings (setting_val, setting_key) VALUES (?, ?)");
    }

    if ($stmt->execute([$final_blob, $db_key])) {
        header("Location: smack-css.php?v=" . $target . "&msg=CALIBRATED");
        exit;
    }
}

// --- 3. READ & SPLIT LOGIC ---
$stmt = $pdo->prepare("SELECT setting_val FROM snap_settings WHERE setting_key = ?");
$stmt->execute([$db_key]);
$raw_data = $stmt->fetchColumn() ?: "";

$pattern = '/\/\* SKIN_START \*\/.*?\/\* SKIN_END \*\//s';
$skin_block = "";
$user_block  = $raw_data;

if (preg_match($pattern, $raw_data, $matches)) {
    $skin_block = $matches[0];
    $user_block = trim(str_replace($skin_block, '', $raw_data));
}

$page_title = "STYLE OVERRIDES";
include 'core/admin-header.php';
include 'core/sidebar.php';
?>

<div class="main">

    <div class="header-row header-row--ruled">
        <h2>STYLE OVERRIDES: <?php echo strtoupper($target); ?></h2>
        <div class="header-actions">
            <a href="smack-css.php?v=public" class="css-tab <?php echo ($target === 'public') ? 'css-tab-active' : ''; ?>">PUBLIC SITE</a>
            <a href="smack-css.php?v=admin"  class="css-tab <?php echo ($target === 'admin')  ? 'css-tab-active' : ''; ?>">ADMIN PANEL</a>
        </div>
    </div>

    <?php if (isset($_GET['msg'])): ?>
        <div class="alert">> ARCHITECTURE CALIBRATED</div>
    <?php endif; ?>

    <form method="POST">

        <?php if ($skin_block): ?>
        <div class="box">
            <p class="css-readonly-label">GENERATED BY SKIN ADMIN (READ ONLY)</p>
            <pre class="css-preview-block"><?php echo htmlspecialchars($skin_block); ?></pre>
            <input type="hidden" name="skin_css_buffer" value="<?php echo htmlspecialchars($skin_block); ?>">
        </div>
        <?php else: ?>
            <input type="hidden" name="skin_css_buffer" value="">
        <?php endif; ?>

        <div class="box">
            <div class="lens-input-wrapper">
                <label>MANUAL OVERRIDES</label>
                <p class="dim">/* These styles are injected after the main stylesheet. Safe to edit. */</p>
                <textarea name="manual_overrides" class="css-override-textarea" spellcheck="false"><?php echo htmlspecialchars($user_block); ?></textarea>
            </div>
        </div>

        <div class="form-action-row">
            <button type="submit" name="save_overrides" class="master-update-btn">
                SAVE <?php echo strtoupper($target); ?> OVERRIDES
            </button>
        </div>

    </form>

</div>

<?php include 'core/admin-footer.php'; ?>
