<?php
/**
 * SnapSmack - Style Override Manager
 * Version: 2.6 - Dual-Context Protected Blocks
 * * DEV NOTES:
 * This file manages custom CSS stored in the database. It handles two targets: 
 * 'public' (front-end) and 'admin' (back-end). It uses a "Split-Merge" architecture 
 * to protect code generated by the Skin Admin while allowing manual edits.
 */
require_once 'core/auth.php';

$msg = "";

/**
 * 1. TARGET ROUTING
 * We determine which database key to use based on the URL parameter 'target'.
 * ?target=public => custom_css_public
 * ?target=admin  => custom_css_admin
 */
$target = $_GET['target'] ?? 'public'; 
$db_key = ($target === 'admin') ? 'custom_css_admin' : 'custom_css_public';

/**
 * 2. SAVE LOGIC
 * When the form is submitted, we combine the protected skin CSS and the manual 
 * user CSS into a single string to store in the database.
 */
if (isset($_POST['save_css'])) {
    $manual_content = $_POST['manual_css_content'];
    
    // This comes from a hidden field to ensure we don't lose the Skin Admin's work.
    $protected_skin_content = $_POST['skin_css_buffer']; 
    
    // Stitch blocks together. We trim to keep the database row clean of trailing newlines.
    $final_blob = trim($protected_skin_content . "\n\n" . $manual_content);
    
    // Check if the setting key exists; if not, we INSERT. If yes, we UPDATE.
    $check = $pdo->prepare("SELECT COUNT(*) FROM snap_settings WHERE setting_key = ?");
    $check->execute([$db_key]);
    
    if ($check->fetchColumn() > 0) {
        $stmt = $pdo->prepare("UPDATE snap_settings SET setting_val = ? WHERE setting_key = ?");
    } else {
        $stmt = $pdo->prepare("INSERT INTO snap_settings (setting_val, setting_key) VALUES (?, ?)");
    }

    if ($stmt->execute([$final_blob, $db_key])) {
        $msg = "CSS Overrides committed. " . strtoupper($target) . " logic preserved.";
    } else {
        $msg = "Error updating database.";
    }
}

/**
 * 3. READ & SPLIT LOGIC
 * Before displaying the form, we fetch the raw data and use Regular Expressions (Regex)
 * to separate the "Skin Admin" block from your "Manual" code.
 */
$stmt = $pdo->prepare("SELECT setting_val FROM snap_settings WHERE setting_key = ?");
$stmt->execute([$db_key]);
$raw_data = $stmt->fetchColumn() ?: "";

/**
 * REGEX PATTERN EXPLAINED:
 * /      = Start of Regex
 * \* = Match a literal asterisk
 * SKIN_START = The specific marker we look for
 * .*?    = Match any character (non-greedy)
 * \s     = Match newlines as well
 * /      = End of Regex
 */
$pattern = '/\/\* SKIN_START \*\/.*?\/\* SKIN_END \*\//s';
$skin_block = "";
$user_block = $raw_data;

if (preg_match($pattern, $raw_data, $matches)) {
    // We found a skin block! We store it separately for the "Read Only" display.
    $skin_block = $matches[0];
    
    // We remove the skin block from the text we send to the main editor textarea.
    $user_block = trim(str_replace($skin_block, '', $raw_data));
}

$page_title = "CSS Overrides";
include 'core/admin-header.php';
include 'core/sidebar.php';
?>

<div class="main">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
        <h2>STYLE OVERRIDES: <span style="color: #39FF14;"><?php echo strtoupper($target); ?></span></h2>
        
        <div class="target-switcher">
            <a href="?target=public" class="btn <?php echo $target == 'public' ? 'active' : ''; ?>" style="padding: 5px 15px; border: 1px solid #333; text-decoration: none; color: <?php echo $target == 'public' ? '#39FF14' : '#666'; ?>;">[ PUBLIC SITE ]</a>
            <a href="?target=admin" class="btn <?php echo $target == 'admin' ? 'active' : ''; ?>" style="padding: 5px 15px; border: 1px solid #333; text-decoration: none; color: <?php echo $target == 'admin' ? '#39FF14' : '#666'; ?>;">[ ADMIN PANEL ]</a>
        </div>
    </div>

    <?php if($msg): ?>
        <div class="msg">> <?php echo $msg; ?></div>
    <?php endif; ?>

    <form method="POST">
        
        <?php if ($skin_block): ?>
        <div class="box" style="padding: 20px; border-color: #444; background: #0a0a0a; margin-bottom: 20px;">
            <h4 style="margin-top: 0; color: #555; font-size: 0.7rem; letter-spacing: 1px;">GENERATED BY SKIN ADMIN (READ ONLY)</h4>
            <pre style="font-family: monospace; color: #444; font-size: 0.85rem; margin: 0; white-space: pre-wrap;"><?php echo htmlspecialchars($skin_block); ?></pre>
            
            <input type="hidden" name="skin_css_buffer" value="<?php echo htmlspecialchars($skin_block); ?>">
        </div>
        <?php else: ?>
            <input type="hidden" name="skin_css_buffer" value="">
        <?php endif; ?>

        <div class="box">
            <label style="color: #39FF14;">Manual Overrides</label>
            <p class="dim" style="margin-bottom: 10px; font-size: 0.8rem;">/* These styles are injected after the main stylesheet. Safe to edit. */</p>
            <textarea name="manual_css_content" rows="20" spellcheck="false" style="width: 100%; font-family: 'Consolas', 'Monaco', 'Courier New', monospace; background: #000; color: #39FF14; border: 1px solid #333; padding: 20px; font-size: 0.95rem; tab-size: 4; outline: none;"><?php echo htmlspecialchars($user_block); ?></textarea>
            
            <div style="margin-top: 20px; display: flex; gap: 15px;">
                <button type="submit" name="save_css" class="btn-smack">COMMIT MANUAL OVERRIDES</button>
                <a href="smack-admin.php" class="btn-clear" style="display: flex; align-items: center; padding: 0 20px; text-decoration: none;">Cancel</a>
            </div>
        </div>
    </form>
</div>

<?php include 'core/admin-footer.php'; ?>