<?php
/**
 * SNAPSMACK - Single Sign-On Handler
 * Alpha v0.7.8
 *
 * Satellite-side SSO endpoint. Validates a one-time token issued by the hub
 * via the multisite/auth/sso-token API, creates an admin session for the
 * satellite's primary admin user, and redirects to the admin dashboard.
 *
 * Token lifecycle:
 *   - Generated by the satellite on hub request (multisite/auth/sso-token)
 *   - Valid for 5 minutes, single-use
 *   - Invalidated immediately on successful validation
 *
 * Security notes:
 *   - Token is only generated in response to a Bearer-authenticated API call
 *   - Token is 32 random bytes (64 hex chars), compared with hash_equals()
 *   - Session is created identically to a normal admin login
 *   - No password is transmitted at any point
 */

require_once 'core/db.php';

// ─────────────────────────────────────────────────────────────────────────────
// SESSION BOOTSTRAP — match the same session config as auth.php / login.php
// ─────────────────────────────────────────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    $ss_session_dir = __DIR__ . '/data/sessions';
    if (!is_dir($ss_session_dir)) {
        @mkdir($ss_session_dir, 0700, true);
        @file_put_contents($ss_session_dir . '/.htaccess', "Order deny,allow\nDeny from all\n");
    }
    if (is_dir($ss_session_dir) && is_writable($ss_session_dir)) {
        session_save_path($ss_session_dir);
    }
    session_set_cookie_params([
        'lifetime' => 86400,
        'path'     => '/',
        'secure'   => isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on',
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    ini_set('session.gc_maxlifetime', 86400);
    session_start();
}

// Already authenticated — just go to admin
if (isset($_SESSION['user_login'])) {
    header('Location: smack-admin.php');
    exit;
}

// ─────────────────────────────────────────────────────────────────────────────
// VALIDATE TOKEN
// ─────────────────────────────────────────────────────────────────────────────
$token_input = trim($_GET['token'] ?? '');

if (!$token_input || strlen($token_input) !== 64 || !ctype_xdigit($token_input)) {
    sso_fail('Invalid or missing token.');
}

// Load settings
$settings = $pdo->query("SELECT setting_key, setting_val FROM snap_settings")->fetchAll(PDO::FETCH_KEY_PAIR);

$stored_token   = $settings['multisite_sso_token']         ?? '';
$token_expires  = (int)($settings['multisite_sso_token_expires'] ?? 0);

if (!$stored_token) sso_fail('No SSO token on record. Request a new one from the hub.');
if (time() > $token_expires) sso_fail('SSO token has expired. Request a new one from the hub.');
if (!hash_equals($stored_token, $token_input)) sso_fail('Token mismatch.');

// ─────────────────────────────────────────────────────────────────────────────
// SINGLE-USE: Invalidate immediately before creating the session
// ─────────────────────────────────────────────────────────────────────────────
$pdo->prepare("INSERT INTO snap_settings (setting_key, setting_val) VALUES (?, '') ON DUPLICATE KEY UPDATE setting_val = ''")->execute(['multisite_sso_token']);
$pdo->prepare("INSERT INTO snap_settings (setting_key, setting_val) VALUES (?, '0') ON DUPLICATE KEY UPDATE setting_val = '0'")->execute(['multisite_sso_token_expires']);

// ─────────────────────────────────────────────────────────────────────────────
// FIND PRIMARY ADMIN USER
// ─────────────────────────────────────────────────────────────────────────────
$admin = $pdo->query("SELECT id, username, preferred_skin FROM snap_users WHERE user_role = 'admin' ORDER BY id ASC LIMIT 1")->fetch(PDO::FETCH_ASSOC);

if (!$admin) sso_fail('No admin user found on this satellite.');

// ─────────────────────────────────────────────────────────────────────────────
// CREATE SESSION — identical to a successful login in login.php
// ─────────────────────────────────────────────────────────────────────────────
session_regenerate_id(true);
$_SESSION['user_login']          = $admin['username'];
$_SESSION['user_id']             = $admin['id'];
$_SESSION['user_preferred_skin'] = $admin['preferred_skin'] ?: 'midnight-lime';
$_SESSION['sso_login']           = true;  // Flag so audit log / UI can note this was an SSO session

header('Location: smack-admin.php');
exit;

// ─────────────────────────────────────────────────────────────────────────────
// FAIL HANDLER
// ─────────────────────────────────────────────────────────────────────────────
function sso_fail(string $reason): void {
    global $settings;
    $site_name = htmlspecialchars($settings['site_name'] ?? 'SnapSmack');
    http_response_code(403);
    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>SSO Failed — ' . $site_name . '</title>
    <style>body{background:#0a0a0a;color:#ccc;font-family:monospace;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}
    .box{border:1px solid #333;padding:40px;max-width:450px;text-align:center;}
    h2{color:#f44336;margin-top:0;letter-spacing:2px;} p{color:#888;line-height:1.6;}
    a{color:#aaa;}</style></head><body>
    <div class="box"><h2>SSO FAILED</h2><p>' . htmlspecialchars($reason) . '</p>
    <p><a href="login.php">&larr; Login manually</a></p></div></body></html>';
    exit;
}
