<?php
/**
 * SNAPSMACK - Single Sign-On Handler
 *
 * Spoke-side SSO endpoint. Validates a one-time token issued by the hub
 * via the multisite/auth/sso-token API, creates an admin session for the
 * spoke's primary admin user, and redirects to the admin dashboard.
 *
 * Token lifecycle:
 *   - Generated by the spoke on hub request (multisite/auth/sso-token)
 *   - Valid for 5 minutes, single-use
 *   - Invalidated immediately on successful validation
 *
 * Security notes:
 *   - Token is only generated in response to a Bearer-authenticated API call
 *   - Token is 32 random bytes (64 hex chars), compared with hash_equals()
 *   - Session is created identically to a normal admin login
 *   - No password is transmitted at any point
 */

/**
 * SNAPSMACK_EOF_HEADER
 *     // ===== SNAPSMACK EOF =====
 * Last non-empty line of this file MUST match the line above.
 * Missing or different = truncated/corrupted. Restore before saving.
 */


require_once 'core/db.php';
require_once 'core/fedboard.php';

// ─────────────────────────────────────────────────────────────────────────────
// SESSION BOOTSTRAP — match the same session config as auth.php / login.php
// ─────────────────────────────────────────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    $ss_session_dir = __DIR__ . '/data/sessions';
    if (!is_dir($ss_session_dir)) {
        @mkdir($ss_session_dir, 0700, true);
        @file_put_contents($ss_session_dir . '/.htaccess', "Order deny,allow\nDeny from all\n");
    }
    if (is_dir($ss_session_dir) && is_writable($ss_session_dir)) {
        session_save_path($ss_session_dir);
    }
    session_set_cookie_params([
        'lifetime' => 86400,
        'path'     => '/',
        // SECAUDIT 047: honour the reverse-proxy TLS header too. On the common
        // cPanel/shared-host setup PHP sees plain HTTP behind a TLS-terminating
        // proxy, so the old check left the admin session cookie without Secure.
        'secure'   => (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on')
                   || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https'),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    ini_set('session.gc_maxlifetime', 86400);
    session_start();
}

// ─────────────────────────────────────────────────────────────────────────────
// VALIDATE TOKEN
// ─────────────────────────────────────────────────────────────────────────────
$token_input = trim($_GET['token'] ?? '');

// Load settings before any failure so the error page can name this site.
$settings = $pdo->query("SELECT setting_key, setting_val FROM snap_settings")->fetchAll(PDO::FETCH_KEY_PAIR);

if (!$token_input || strlen($token_input) !== 64 || !ctype_xdigit($token_input)) {
    sso_fail('That one-time sign-in ticket is no longer valid. Return to the hub and try again.');
}

// ─────────────────────────────────────────────────────────────────────────────
// SINGLE-USE: lock and delete the destination-bound ticket atomically.
// ─────────────────────────────────────────────────────────────────────────────
$destination = 'admin';
$requested_by = '';
fb_ensure_tables($pdo);
$pdo->beginTransaction();
try {
    $hash = hash('sha256', $token_input);
    $ticket_q = $pdo->prepare("SELECT id,token_hash,destination,requested_by,expires_at
                               FROM snap_multisite_sso_tokens WHERE token_hash=? FOR UPDATE");
    $ticket_q->execute([$hash]);
    $ticket = $ticket_q->fetch(PDO::FETCH_ASSOC);
    if ($ticket && hash_equals((string)$ticket['token_hash'], $hash)
        && strtotime((string)$ticket['expires_at']) >= time()) {
        $destination = in_array(($ticket['destination'] ?? ''), ['admin','fedboard'], true)
            ? (string)$ticket['destination'] : 'admin';
        $requested_by = (string)($ticket['requested_by'] ?? '');
        $pdo->prepare("DELETE FROM snap_multisite_sso_tokens WHERE id=?")->execute([(int)$ticket['id']]);
        $pdo->commit();
    } else {
        if ($ticket) $pdo->prepare("DELETE FROM snap_multisite_sso_tokens WHERE id=?")->execute([(int)$ticket['id']]);
        $pdo->commit();
        sso_fail('That one-time sign-in ticket is no longer valid. Return to the hub and try again.');
    }
} catch (Throwable $e) {
    if ($pdo->inTransaction()) $pdo->rollBack();
    sso_fail('The one-time sign-in ticket could not be verified. Return to the hub and try again.', $destination);
}

// ─────────────────────────────────────────────────────────────────────────────
// FIND PRIMARY ADMIN USER
// ─────────────────────────────────────────────────────────────────────────────
$admin = $pdo->query("SELECT id, username, user_role, preferred_skin FROM snap_users WHERE user_role = 'admin' ORDER BY id ASC LIMIT 1")->fetch(PDO::FETCH_ASSOC);

if (!$admin) sso_fail('No admin user found on this spoke.', $destination);

// ─────────────────────────────────────────────────────────────────────────────
// CREATE SESSION — identical to a successful login in login.php
// ─────────────────────────────────────────────────────────────────────────────
if (!isset($_SESSION['user_login'])) {
    session_regenerate_id(true);
    $_SESSION['user_login']          = $admin['username'];
    $_SESSION['user_id']             = $admin['id'];
    $_SESSION['user_role']           = $admin['user_role'] ?: 'admin';
    $_SESSION['user_preferred_skin'] = $admin['preferred_skin'] ?: 'midnight-lime';
    $_SESSION['sso_login']           = true;
}

fb_audit($pdo, 'spoke', $requested_by, $destination, 'consumed', (int)$admin['id']);
header('Referrer-Policy: no-referrer');
header('Location: ' . ($destination === 'fedboard' ? 'pixel.php' : 'smack-admin.php'));
exit;

// ─────────────────────────────────────────────────────────────────────────────
// FAIL HANDLER
// ─────────────────────────────────────────────────────────────────────────────
function sso_fail(string $reason, string $destination = 'admin'): void {
    global $settings;
    header('Referrer-Policy: no-referrer');
    $site_name = htmlspecialchars($settings['site_name'] ?? 'SnapSmack');
    http_response_code(403);
    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>SSO Failed — ' . $site_name . '</title>
    <style>body{background:#0a0a0a;color:#ccc;font-family:monospace;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}
    .box{border:1px solid #333;padding:40px;max-width:450px;text-align:center;}
    h2{color:#f44336;margin-top:0;letter-spacing:2px;} p{color:#888;line-height:1.6;}
    a{color:#aaa;}</style></head><body>
    <div class="box"><h2>' . ($destination === 'fedboard' ? 'FEDBOARD COULD NOT SWITCH SITES' : 'SSO FAILED') . '</h2><p>' . htmlspecialchars($reason) . '</p>
    <p><a href="snap-in">LOG IN MANUALLY</a></p></div></body></html>';
    exit;
}
// ===== SNAPSMACK EOF =====
