<?php
declare(strict_types=1);
$root=dirname(__DIR__);$catalog=json_decode((string)file_get_contents($root.'/assets/ASSET-INVENTORY.json'),true,512,JSON_THROW_ON_ERROR);require_once $root.'/core/asset-registry.php';
if(($catalog['schema_version']??'')!=='1.1')throw new RuntimeException('Asset security inventory schema is stale.');
$expected=[];foreach(['js'=>'javascript','css'=>'css'] as $dir=>$group){foreach(glob($root.'/assets/'.$dir.'/*')?:[] as $path){if(is_file($path)&&!str_ends_with($path,'.bak'))$expected['assets/'.$dir.'/'.basename($path)]=$group;}}
$seen=[];foreach(['javascript','css'] as $group){foreach($catalog[$group]??[] as $entry){$file=$entry['file']??'';if(isset($seen[$file]))throw new RuntimeException("Duplicate asset: {$file}");$seen[$file]=true;if(($expected[$file]??'')!==$group)throw new RuntimeException("Unknown inventory asset: {$file}");foreach(['owner','scope','callers','security_signals','security_review','purpose','registry_handle'] as $field)if(!array_key_exists($field,$entry))throw new RuntimeException("{$file} lacks {$field}");if(($entry['owner']??'')!=='cms')throw new RuntimeException("{$file} is not CMS-owned");if(snapsmack_asset_by_handle((string)$entry['registry_handle'])===null)throw new RuntimeException("{$file} has no working registry handle");if(!in_array($entry['scope']??'',['public','admin','tool'],true))throw new RuntimeException("{$file} has invalid scope");if(!is_array($entry['callers'])||$entry['callers']===[])throw new RuntimeException("{$file} lacks callers");if(in_array('CMS runtime',$entry['callers'],true))throw new RuntimeException("{$file} uses a placeholder instead of exact callers");if(($entry['security_signals']??[])!==[]&&(!is_array($entry['security_review']??null)||($entry['security_review']['signals']??null)!==$entry['security_signals']||trim((string)($entry['security_review']['review']??''))===''))throw new RuntimeException("{$file} has unreviewed security signals");}}
$missing=array_diff_key($expected,$seen);if($missing)throw new RuntimeException('Uninventoried assets: '.implode(', ',array_keys($missing)));
$adminOnly='~^(?:smack-|login\.php$|snap-in\.php$|community-auth\.php$|core/(?:admin|csrf|photo-editor|ai-|update|skin-admin))~';foreach(['javascript','css'] as $group){foreach($catalog[$group]??[] as $entry){$callers=$entry['callers']??[];if($callers!==[]&&count(array_filter($callers,fn($caller)=>is_string($caller)&&preg_match($adminOnly,$caller)))===count($callers)&&($entry['scope']??'')!=='admin')throw new RuntimeException(($entry['file']??'asset').' exposes an admin-only asset as '.($entry['scope']??'unknown'));}}
$legacy=require $root.'/core/manifest-inventory.php';foreach(($legacy['scripts']??[]) as $handle=>$entry){foreach(['path','css'] as $field){if(!isset($entry[$field]))continue;$path=(string)$entry[$field];if(!is_file($root.'/'.$path))throw new RuntimeException("Stale asset handle {$handle} points to missing {$path}");}}
if(snapsmack_skin_declared_assets(['require_scripts'=>['asset:admin:ss-engine-admin-ui'],'require_styles'=>['asset:admin:admin-theme-geometry-master']])!==['scripts'=>[],'styles'=>[]])throw new RuntimeException('Strict skin asset resolution crossed into admin scope.');
echo "Complete JS/CSS security inventory regression passed.\n";
