<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="chaplin-v2<?php echo ($view['response']['kind'] ?? '') === 'landing' ? ' chap-landing' : ''; ?>" data-chap-card="<?php echo snap_escape_attr($view['site']['skin_presentation']['chaplin']['card_style'] ?? ''); ?>" data-chap-flicker="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['chap_flicker'] ?? ''); ?>" data-chap-scratch-frequency="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['chap_scratch_freq'] ?? ''); ?>"><canvas id="chap-film-bg" aria-hidden="true"></canvas><header id="rg-header" data-sticky-header><div class="rg-header-inside"><a class="rg-logo-link" href="<?php echo snap_route_url('home'); ?>"><span class="rg-masthead"><?php echo snap_escape_html($view['site']['site_name']); ?></span></a><nav class="rg-header-nav"><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></nav></div></header>
<main id="scroll-stage" class="public-content<?php echo ($view['response']['kind'] ?? '') === 'landing' ? ' chap-landing' : ''; ?>">
<?php if (($view['response']['kind'] ?? '') === 'landing'): $hero = $view['response']['items'][0] ?? null; ?>
<?php if (is_array($hero)): ?><div id="rg-photobox"><div class="rg-photo-wrap"><a class="chap-landing-link" href="<?php echo snap_escape_url($hero['url'] ?? snap_route_url('photo', ['slug' => $hero['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($hero['img_title'] ?? ''); ?>"><div class="chap-img-frame"><?php if (!empty($view['site']['skin_presentation']['chaplin']['corners'])): ?><div class="chap-frame-deco" aria-hidden="true"><img class="chap-orn chap-orn-tl" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-tr" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-bl" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-br" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""></div><?php endif; ?><img class="rg-image post-image chap-photo" src="<?php echo snap_escape_url($hero['img_file'] ?? $hero['img_thumb_aspect'] ?? ''); ?>" alt="<?php echo snap_escape_attr($hero['img_alt'] ?? $hero['img_title'] ?? ''); ?>" loading="eager"><div class="chap-frame-lines" aria-hidden="true"><div class="chap-line chap-line-top"></div><div class="chap-line chap-line-bot"></div><div class="chap-line chap-line-lft"></div><div class="chap-line chap-line-rgt"></div></div></div></a></div></div><?php if (($view['site']['skin_presentation']['chaplin']['title_position'] ?? '') === 'below_photo'): ?><div class="chap-intertitle"><div class="chap-intertitle-rule"></div><div class="chap-intertitle-title"><?php echo snap_escape_html($hero['img_title'] ?? ''); ?></div><?php if (!empty($hero['img_date'])): ?><div class="chap-intertitle-date"><?php echo snap_escape_html($hero['img_date']); ?></div><?php endif; ?><div class="chap-intertitle-rule"></div></div><?php endif; ?><div id="infobox" aria-hidden="true"></div><?php else: ?><div id="rg-photobox" class="chap-photobox-empty"><p class="chap-no-photos">The projector is dark.</p></div><?php endif; ?>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post' || ($view['response']['kind'] ?? '') === 'page' || ($view['response']['kind'] ?? '') === 'collection'): ?>
<article id="photobox" class="h-entry single-image-page">
<?php if (($view['site']['skin_presentation']['chaplin']['title_position'] ?? '') === 'above_photo'): ?><h1 class="p-name photo-title-header"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? $view['response']['item']['name'] ?? ''); ?></h1><?php endif; ?>
<?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><div class="u-photo post-image-wrap chap-img-frame">
<?php if (!empty($view['site']['skin_presentation']['chaplin']['corners'])): ?><div class="chap-frame-deco" aria-hidden="true"><img class="chap-orn chap-orn-tl" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-tr" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-bl" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""><img class="chap-orn chap-orn-br" src="<?php echo snap_escape_url($view['site']['skin_presentation']['chaplin']['corner_asset']); ?>" alt=""></div><?php endif; ?>
<?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'post-image'])); ?><div class="chap-frame-lines" aria-hidden="true"><div class="chap-line chap-line-top"></div><div class="chap-line chap-line-bot"></div><div class="chap-line chap-line-lft"></div><div class="chap-line chap-line-rgt"></div></div></div><?php endif; ?>
<?php if (($view['site']['skin_presentation']['chaplin']['title_position'] ?? '') !== 'above_photo'): ?><h1 class="p-name photo-title-footer"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? $view['response']['item']['name'] ?? ''); ?></h1><?php endif; ?>
<?php if (!empty($view['response']['item']['img_date']) || !empty($view['response']['item']['created_at'])): ?><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?>"><?php echo snap_escape_html($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?></time><?php endif; ?><?php if (!empty($view['site']['owner_name'])): ?><span class="p-author h-card"><span class="p-name"><?php echo snap_escape_html($view['site']['owner_name']); ?></span></span><?php endif; ?>
<?php if (($view['site']['skin_presentation']['chaplin']['show_description'] ?? false)): ?><div id="infobox" class="entry-content e-content static-transmission"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div><?php endif; ?></article>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><section class="search-results"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? 'Search'); ?></h1><?php foreach (($view['response']['results'] ?? []) as $group): ?><?php foreach ($group as $item): ?><article><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? ''); ?></h2></article><?php endforeach; ?><?php endforeach; ?></section>
<?php elseif (($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'albums' || ($view['response']['kind'] ?? '') === 'collections'): ?><section id="browse-grid" class="fsog-archive-grid archive-grid h-feed"><?php foreach (($view['response']['items'] ?? []) as $item): ?><article class="thumb-container fsog-archive-item"><a class="thumb-link" href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo',['slug'=>$item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php if (!empty($item['img_thumb_square']) || !empty($item['img_thumb_aspect']) || !empty($item['img_file'])): ?><div class="fsog-thumb"><?php echo snap_render_html(snap_render_component('image',['url'=>$item['img_thumb_square'] ?? $item['img_thumb_aspect'] ?? $item['img_file'],'alt'=>$item['img_alt'] ?? $item['img_title'] ?? ''])); ?></div><?php endif; ?><h2 class="fsog-archive-title"><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? $item['name'] ?? ''); ?></h2></a></article><?php endforeach; ?></section><section id="justified-grid" class="ss-scroll-wall"><?php foreach (($view['response']['items'] ?? []) as $item): ?><a class="justified-item ss-masonry-item" href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo',['slug'=>$item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_file'])): ?><?php echo snap_render_html(snap_render_component('image',['url'=>$item['img_thumb_aspect'] ?? $item['img_file'],'alt'=>$item['img_alt'] ?? $item['img_title'] ?? ''])); ?><?php endif; ?></a><?php endforeach; ?></section>
<?php else: ?><section class="not-found"><h1>Not found</h1></section><?php endif; ?>
<?php if (!empty($view['response']['comments'])): ?><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments']])); ?><?php endif; ?></main>
<footer id="system-footer" class="site-footer"><div id="footer" class="inside"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer><?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
