<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?></head>
<body class="new-horizon-v2"><header id="header" class="site-header" data-sticky-header><div class="inside"><a class="site-title logo-area" href="<?php echo snap_route_url('home'); ?>"><span class="site-title-text"><?php echo snap_escape_html($view['site']['site_name']); ?></span></a><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></div></header>
<main id="scroll-stage" class="public-content">
<?php if (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post' || ($view['response']['kind'] ?? '') === 'page' || ($view['response']['kind'] ?? '') === 'collection'): ?>
<article class="h-entry single-image-page"><div id="photobox"><div class="main-photo u-photo"><?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'post-image'])); ?><?php endif; ?></div></div>
<div id="infobox"><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></div>
<div id="footer"><div id="pane-info" class="footer-pane"><h2 class="p-name photo-title-footer"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h2><?php if (!empty($view['response']['item']['img_date']) || !empty($view['response']['item']['created_at'])): ?><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?>"><?php echo snap_escape_html($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?></time><?php endif; ?><?php if (!empty($view['site']['owner_name'])): ?><span class="p-author h-card"><span class="p-name"><?php echo snap_escape_html($view['site']['owner_name']); ?></span></span><?php endif; ?><div class="description entry-content e-content"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div>
<div class="meta"><div class="meta-header">TECHNICAL SPECIFICATIONS</div><table class="exif-table"><?php if (!empty($view['response']['item']['Model'])): ?><tr><td class="exif-label">Model</td><td class="exif-value"><?php echo snap_escape_html($view['response']['item']['Model']); ?></td></tr><?php endif; ?><?php if (!empty($view['response']['item']['lens'])): ?><tr><td class="exif-label">Lens</td><td class="exif-value"><?php echo snap_escape_html($view['response']['item']['lens']); ?></td></tr><?php endif; ?><?php if (!empty($view['response']['item']['FNumber'])): ?><tr><td class="exif-label">Aperture</td><td class="exif-value"><?php echo snap_escape_html($view['response']['item']['FNumber']); ?></td></tr><?php endif; ?><?php if (!empty($view['response']['item']['ExposureTime'])): ?><tr><td class="exif-label">Shutter</td><td class="exif-value"><?php echo snap_escape_html($view['response']['item']['ExposureTime']); ?></td></tr><?php endif; ?><?php if (!empty($view['response']['item']['ISOSpeedRatings'])): ?><tr><td class="exif-label">ISO</td><td class="exif-value"><?php echo snap_escape_html($view['response']['item']['ISOSpeedRatings']); ?></td></tr><?php endif; ?></table></div></div><div id="pane-comments" class="footer-pane"><?php if (!empty($view['response']['comments'])): ?><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments']])); ?><?php endif; ?></div></div></article>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><section class="search-results"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? 'Search'); ?></h1><?php foreach (($view['response']['results'] ?? []) as $group): ?><?php foreach ($group as $item): ?><article><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? ''); ?></h2></article><?php endforeach; ?><?php endforeach; ?></section>
<?php elseif (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'albums' || ($view['response']['kind'] ?? '') === 'collections'): ?><section id="browse-grid" class="square-grid public-grid h-feed archive-grid"><?php foreach (($view['response']['items'] ?? []) as $item): ?><article class="thumb-container"><a class="thumb-link" href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>"><?php if (!empty($item['img_thumb_square']) || !empty($item['img_thumb_aspect']) || !empty($item['img_file'])): ?><?php echo snap_render_html(snap_render_component('image',['url'=>$item['img_thumb_square'] ?? $item['img_thumb_aspect'] ?? $item['img_file'],'alt'=>$item['img_alt'] ?? $item['img_title'] ?? ''])); ?><?php endif; ?><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? $item['name'] ?? ''); ?></h2></a></article><?php endforeach; ?></section>
<?php else: ?><section class="not-found"><h1>Not found</h1></section><?php endif; ?>
</main>
<footer id="system-footer" class="site-footer"><div class="inside"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer><?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
