<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="parade-v2"><div class="pa-parade-bg pa-flag-bg" aria-hidden="true" data-flag-wave data-stripes="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['stripes']); ?>" data-orientation="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['orientation']); ?>" data-speed="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['speed']); ?>" data-amplitude="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['amplitude']); ?>" data-opacity="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['opacity']); ?>" data-pa-palette="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['stripes']); ?>" data-pa-border-style="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['border_style']); ?>" data-pa-border-dir="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['border_dir']); ?>" data-pa-border-rhythm="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['border_rhythm']); ?>" data-pa-border-cycle="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['border_cycle']); ?>" data-pa-border-minl="<?php echo snap_escape_attr($view['site']['skin_presentation']['flag']['border_minl']); ?>"></div><div class="pa-panel" aria-hidden="true"></div><div class="pa-content-wrap landing-feed">
<?php if (($view['site']['skin_presentation']['options']['pa_profile_header'] ?? '') === '1'): ?><header class="pa-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="pa-profile-avatar"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt=""></div><?php else: ?><div class="pa-profile-avatar pa-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></div><?php endif; ?>
<div class="pa-profile-info"><div class="pa-profile-nameline"><h1 class="pa-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['pa_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="pa-profile-tagline-sep">/</span><p class="pa-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div><div class="pa-profile-stats"><span class="pa-profile-stat"><strong class="pa-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></strong><span class="pa-profile-stat-label">posts</span></span></div><?php if (!empty($view['site']['site_description'])): ?><p class="pa-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></header><?php endif; ?>
<nav class="pa-sticky-nav" aria-label="Primary"><div class="pa-sticky-nav-inner"><ul class="pa-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag'): ?><main><div id="browse-grid" class="pa-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="pa-tile"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post'): ?><main><article class="pa-post-ig"><div class="pa-post-ig-image"><?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'pa-single-img'])); ?><?php endif; ?></div><div class="pa-post-ig-info"><div class="pa-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="pa-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="pa-static-page"><h1 class="pa-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="pa-static-content"><div class="pa-static-body description"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></div></article></main>
<?php else: ?><main><section class="pa-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer"><div id="footer"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div><?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
