<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="photogram-v2"><div id="pg-app"><div class="pg-content">
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'albums' || ($view['response']['kind'] ?? '') === 'collections'): ?>
<header class="pg-profile-header"><span class="pg-profile-header-title"><?php echo snap_escape_html($view['site']['site_name']); ?></span></header>
<section class="pg-profile" aria-label="Profile"><div class="pg-profile-top">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="pg-avatar"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="<?php echo snap_escape_attr($view['site']['site_name']); ?>" width="80" height="80"></div><?php else: ?><div class="pg-avatar-placeholder" aria-hidden="true"></div><?php endif; ?>
<div class="pg-profile-stats"><div class="pg-stat"><span class="pg-stat-count"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="pg-stat-label">Posts</span></div><div class="pg-stat"><span class="pg-stat-count"><?php echo snap_escape_html($view['response']['like_count'] ?? ''); ?></span><span class="pg-stat-label">Likes</span></div><div class="pg-stat"><span class="pg-stat-count"><?php echo snap_escape_html($view['response']['comment_count'] ?? ''); ?></span><span class="pg-stat-label">Comments</span></div></div></div>
<?php if (!empty($view['site']['site_description'])): ?><div class="pg-profile-bio"><p class="pg-bio-text"><?php echo snap_escape_html($view['site']['site_description']); ?></p></div><?php endif; ?></section><div class="pg-divider"></div><?php if (!empty($view['site']['skin_presentation']['discover']['visible'])): ?><section class="pg-discover" aria-label="Discover"><h2 class="pg-discover-heading">Discover</h2><?php echo snap_render_html(snap_render_component('navigation',['items'=>$view['response']['navigation'] ?? []])); ?></section><?php endif; ?>
<main class="pg-grid h-feed" id="pg-grid" aria-label="Photos"><?php foreach (($view['response']['items'] ?? []) as $item): ?><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" class="pg-grid-cell" title="<?php echo snap_escape_attr($item['img_title'] ?? $item['title'] ?? ''); ?>"><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><?php echo snap_render_html(snap_render_component('image', ['url'=>$item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'],'alt'=>$item['img_alt'] ?? $item['img_title'] ?? ''])); ?><?php endif; ?><?php if (!empty($item['image_count'])): ?><span class="pg-carousel-badge"><?php echo snap_escape_html($item['image_count']); ?></span><?php endif; ?></a><?php endforeach; ?><?php if (empty($view['response']['items'])): ?><div class="pg-grid-empty">No photos yet.</div><?php endif; ?></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post' || ($view['response']['kind'] ?? '') === 'collection'): ?>
<header class="pg-top-bar"><a class="pg-top-bar-btn pg-back-btn" href="<?php echo snap_route_url('home'); ?>" aria-label="Back">&#x2039;</a><span class="pg-top-bar-title">Post</span><span class="pg-top-bar-btn" aria-hidden="true">&#x2026;</span></header>
<article class="h-entry"><div class="pg-post-author"><?php if (!empty($view['site']['avatar_url'])): ?><span class="pg-post-avatar"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt=""></span><?php else: ?><span class="pg-post-avatar-placeholder"></span><?php endif; ?><div class="pg-post-author-info"><span class="pg-post-author-name p-author"><?php echo snap_escape_html($view['site']['site_name']); ?></span><span class="pg-post-author-sub p-name"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></span></div></div>
<div class="pg-post-image-wrap"><?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image',['url'=>$view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'],'alt'=>$view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '','class'=>'pg-post-image u-photo'])); ?><?php endif; ?></div>
<div class="pg-action-bar"><button class="pg-action-btn pg-like-btn" type="button" aria-label="Like">&#x2661;</button><button class="pg-action-btn pg-comment-btn" type="button" aria-label="Comment">&#x25A1;</button></div><?php if (!empty($view['response']['item']['like_count'])): ?><div class="pg-like-count"><?php echo snap_escape_html($view['response']['item']['like_count']); ?> likes</div><?php endif; ?><div class="pg-caption e-content"><span class="pg-caption-username"><?php echo snap_escape_html($view['site']['site_name']); ?></span> <?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div><?php if (!empty($view['response']['item']['img_date'])): ?><time class="pg-post-time dt-published" datetime="<?php echo snap_escape_attr($view['response']['item']['img_date']); ?>"><?php echo snap_escape_html($view['response']['item']['img_date']); ?></time><?php endif; ?></article>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main class="pg-page-content"><h1 class="pg-page-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="pg-page-body static-content"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><main class="pg-search-wrap"><h1 class="pg-section-label"><?php echo snap_escape_html($view['response']['page_title'] ?? 'Search'); ?></h1><?php foreach (($view['response']['results'] ?? []) as $group): ?><?php foreach ($group as $item): ?><a class="pg-search-meta" href="<?php echo snap_escape_url($item['url'] ?? '#'); ?>"><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? ''); ?></a><?php endforeach; ?><?php endforeach; ?></main>
<?php else: ?><main class="pg-grid-empty"><h1>Not found</h1></main><?php endif; ?>
</div></div><?php echo snap_render_html(snap_render_component('registered-assets',['assets'=>$view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?></body></html>

