<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<?php if (!empty($view['response']['fragment']) && ($view['response']['kind'] ?? '') === 'photo'): ?>
<?php echo snap_render_html(snap_render_component('grid-photo-fragment', ['prefix' => 'jt', 'item' => $view['response']['item'] ?? [], 'photographs' => $view['response']['photographs'] ?? [], 'comments' => $view['response']['comments'] ?? [], 'site' => $view['site']])); ?>
<?php else: ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="jive-turkey-v2 route-<?php echo snap_escape_attr($view['response']['kind'] ?? 'unknown'); ?>" data-carousel-indicator="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['carousel_indicator'] ?? ''); ?>" data-hover-overlay="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['hover_overlay'] ?? ''); ?>" data-nav-line-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['nav_line_mode'] ?? ''); ?>" data-solo-backdrop-source="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['solo_backdrop_source'] ?? ''); ?>">
<div class="jt-jive-turkey-bg" aria-hidden="true" data-jt-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['mode']); ?>" data-jt-scrolls-axis="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['scrolls_axis']); ?>" data-jt-scrolls-fade="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['scrolls_fade']); ?>" data-jt-colourway="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['colourway']); ?>" data-jt-colourways='<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['colourways']); ?>' data-jt-palette='<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['palette']); ?>' data-jt-field="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['field']); ?>" data-jt-speed="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['speed']); ?>" data-jt-cycle="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['cycle']); ?>" data-jt-random-colour="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['random']); ?>" data-jt-border-enabled="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border']); ?>" data-jt-border-width="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border_width']); ?>" data-jt-border-speed="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border_speed']); ?>" data-jt-border-wave="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border_wave']); ?>" data-jt-border-trans="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border_trans']); ?>" data-jt-border-dir="<?php echo snap_escape_attr($view['site']['skin_presentation']['jive']['border_dir']); ?>"></div><div class="jt-panel" aria-hidden="true"></div><div class="jt-content-wrap landing-feed">
<?php if (!empty($view['site']['skin_presentation']['treatment']['enabled'])): ?><div class="jt-treatment-bg" data-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['treatment']['mode']); ?>" data-image="<?php echo snap_escape_url($view['site']['skin_presentation']['treatment']['image']); ?>" data-position="<?php echo snap_escape_attr($view['site']['skin_presentation']['treatment']['position']); ?>" aria-hidden="true"></div><div class="jt-treatment-overlay" aria-hidden="true"></div><?php endif; ?>
<?php if (($view['site']['skin_presentation']['options']['jt_profile_header'] ?? '') === '1'): ?><section class="jt-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="jt-profile-avatar jt-profile-avatar--zoom"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="Profile avatar"></div><?php else: ?><div class="jt-profile-avatar"><span class="jt-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div><?php endif; ?>
<div class="jt-profile-info"><div class="jt-profile-nameline"><h1 class="jt-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['jt_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="jt-profile-tagline-sep">/</span><p class="jt-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div>
<div class="jt-profile-stats"><div class="jt-profile-stat"><span class="jt-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="jt-profile-stat-label">posts</span></div></div><?php if (!empty($view['site']['site_description'])): ?><p class="jt-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></section><?php endif; ?>
<nav class="jt-sticky-nav" aria-label="Site navigation"><div class="jt-sticky-nav-inner"><ul class="jt-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'photo'): ?><main><div id="browse-grid" class="jt-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="<?php echo snap_escape_attr($item['presentation_class'] ?? 'jt-tile'); ?>" style="<?php echo snap_escape_attr($item['frame_style'] ?? ''); ?>" data-trigram-id="<?php echo snap_escape_attr($item['trigram_id'] ?? ''); ?>" data-trigram-slot="<?php echo snap_escape_attr($item['trigram_slot'] ?? ''); ?>"><div class="jt-ring" aria-hidden="true"></div><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['presentation_title'] ?? $item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['presentation_image'] ?? $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['presentation_title'] ?? $item['img_title'] ?? ''])); ?></a><?php if (!empty($item['is_carousel']) && ($view['site']['skin_presentation']['grid']['carousel_indicator'] ?? 'icon') !== 'none'): ?><div class="jt-tile-indicator"><?php if (($view['site']['skin_presentation']['grid']['carousel_indicator'] ?? 'icon') === 'count'): ?><span class="jt-tile-indicator--count"><?php echo snap_escape_html($item['image_count'] ?? ''); ?></span><?php else: ?><span class="jt-tile-indicator--icon" aria-label="<?php echo snap_escape_attr($item['image_count'] ?? ''); ?> images">⧉</span><?php endif; ?></div><?php endif; ?><?php if (($view['site']['skin_presentation']['grid']['hover_overlay'] ?? 'title') === 'title' || ($view['site']['skin_presentation']['grid']['hover_overlay'] ?? 'title') === 'count'): ?><div class="jt-tile-overlay" aria-hidden="true"><span class="jt-tile-overlay-text"><?php if (($view['site']['skin_presentation']['grid']['hover_overlay'] ?? 'title') === 'count'): ?><?php echo snap_escape_html($item['image_count'] ?? '1'); ?> image<?php if (($item['image_count'] ?? 1) != 1): ?>s<?php endif; ?><?php else: ?><?php echo snap_escape_html($item['presentation_title'] ?? $item['img_title'] ?? ''); ?><?php endif; ?></span></div><?php elseif (($view['site']['skin_presentation']['grid']['hover_overlay'] ?? 'title') === 'dark'): ?><div class="jt-tile-overlay jt-tile-overlay--dark" aria-hidden="true"></div><?php endif; ?></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post'): ?><main><article class="jt-post-ig"><div class="jt-post-ig-image">
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="jt-carousel-wrap"><div id="tg-carousel" class="ss-slider" data-slider-mode="carousel"><div class="slider-track"><?php foreach ($view['response']['photographs'] as $photograph): ?><div class="slider-slide<?php if (!empty($photograph['is_framed'])): ?> jt-slide--framed<?php endif; ?>" data-image-id="<?php echo snap_escape_attr($photograph['id'] ?? ''); ?>" style="<?php echo snap_escape_attr($photograph['frame_style'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $photograph['img_file'] ?? '', 'alt' => $photograph['img_alt'] ?? $photograph['img_title'] ?? '', 'attributes' => ['data-lightbox-src' => $photograph['img_file'] ?? '']])); ?></div><?php endforeach; ?></div></div></div>
<?php elseif (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'jt-single-img'])); ?><?php endif; ?></div><div class="jt-post-ig-info"><div class="jt-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="jt-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="jt-static-page jt-static-content"><h1 class="jt-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="jt-static-body"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></article></main>
<?php else: ?><main><section class="jt-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="ss-slider-dots" data-slider-indicators><?php foreach ($view['response']['photographs'] as $slideIndex => $photograph): ?><button type="button" class="ss-slider-dot<?php if ($slideIndex === 0): ?> is-active<?php endif; ?>" data-slide-index="<?php echo snap_escape_attr($slideIndex); ?>" aria-label="<?php echo snap_escape_attr($photograph['img_title'] ?? 'Photograph'); ?>"></button><?php endforeach; ?></div><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer"><div id="footer"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div>
<div id="jt-modal-overlay" class="jt-modal-overlay" hidden data-grid-url="<?php echo snap_route_url('home'); ?>"<?php if (!empty($view['response']['autoopen'])): ?> data-autoopen="1"<?php endif; ?>><div class="jt-modal-backdrop"></div><div id="jt-modal-frame" class="jt-modal-frame"></div></div><div id="jt-lightbox" class="jt-lightbox" hidden><button type="button" class="jt-lightbox-close" aria-label="Close">&times;</button><img class="jt-lightbox-img" src="" alt=""></div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
<?php endif; ?>
