<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="heuristic-v2">
<div class="he-memory-centre" aria-hidden="true" data-heuristic-memory data-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['mode']); ?>" data-first-delay="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['first_delay']); ?>" data-hold="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['hold']); ?>" data-rest="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['rest']); ?>" data-pulses="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['pulses']); ?>" data-memory="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['memory']); ?>" data-infomatics="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['infomatics']); ?>" data-classic-fallback="<?php echo snap_escape_attr($view['site']['skin_presentation']['heuristic']['classic_fallback']); ?>"></div><div class="he-panel" aria-hidden="true"></div><div class="he-content-wrap landing-feed">
<?php if (($view['site']['skin_presentation']['options']['he_profile_header'] ?? '') === '1'): ?><section class="he-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="he-profile-avatar he-profile-avatar--zoom"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="Profile avatar"></div><?php else: ?><div class="he-profile-avatar"><span class="he-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div><?php endif; ?>
<div class="he-profile-info"><div class="he-profile-nameline"><h1 class="he-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['he_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="he-profile-tagline-sep">/</span><p class="he-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div>
<div class="he-profile-stats"><div class="he-profile-stat"><span class="he-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="he-profile-stat-label">posts</span></div></div><?php if (!empty($view['site']['site_description'])): ?><p class="he-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></section><?php endif; ?>
<nav class="he-sticky-nav" aria-label="Site navigation"><div class="he-sticky-nav-inner"><ul class="he-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag'): ?><main><div id="browse-grid" class="he-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="he-tile<?php if (!empty($item['is_framed'])): ?> he-tile--framed<?php endif; ?>" style="<?php echo snap_escape_attr($item['frame_style'] ?? ''); ?>" data-he-code="<?php echo snap_escape_attr($item['heuristic']['code'] ?? ''); ?>" data-he-label="<?php echo snap_escape_attr($item['heuristic']['label'] ?? ''); ?>" data-he-colour="<?php echo snap_escape_attr($item['heuristic']['colour'] ?? 'calm'); ?>" data-he-value="<?php echo snap_escape_attr($item['heuristic']['value'] ?? ''); ?>" data-he-post="<?php echo snap_escape_attr($item['heuristic']['post'] ?? 0); ?>"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post'): ?><main><article class="he-post-ig"><div class="he-post-ig-image">
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="he-carousel-wrap"><div id="tg-carousel" class="ss-slider" data-slider-mode="carousel"><div class="slider-track"><?php foreach ($view['response']['photographs'] as $photograph): ?><div class="slider-slide<?php if (!empty($photograph['is_framed'])): ?> he-slide--framed<?php endif; ?>" data-image-id="<?php echo snap_escape_attr($photograph['id'] ?? ''); ?>" style="<?php echo snap_escape_attr($photograph['frame_style'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $photograph['img_file'] ?? '', 'alt' => $photograph['img_alt'] ?? $photograph['img_title'] ?? '', 'attributes' => ['data-lightbox-src' => $photograph['img_file'] ?? '']])); ?></div><?php endforeach; ?></div></div></div>
<?php elseif (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'he-single-img'])); ?><?php endif; ?></div><div class="he-post-ig-info"><div class="he-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="he-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="he-static-page"><h1 class="he-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="he-static-content"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></article></main>
<?php else: ?><main><section class="he-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="ss-slider-dots" data-slider-indicators><?php foreach ($view['response']['photographs'] as $slideIndex => $photograph): ?><button type="button" class="ss-slider-dot<?php if ($slideIndex === 0): ?> is-active<?php endif; ?>" data-slide-index="<?php echo snap_escape_attr($slideIndex); ?>" aria-label="<?php echo snap_escape_attr($photograph['img_title'] ?? 'Photograph'); ?>"></button><?php endforeach; ?></div><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer"><div id="footer"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div>
<div id="he-modal-overlay" class="he-modal-overlay" hidden data-grid-url="<?php echo snap_route_url('home'); ?>"><div class="he-modal-backdrop"></div><div id="he-modal-frame" class="he-modal-frame"></div></div><div id="he-lightbox" class="he-lightbox" hidden><button type="button" class="he-lightbox-close" aria-label="Close">&times;</button><img class="he-lightbox-img" src="" alt=""></div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
