<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<?php if (!empty($view['response']['fragment']) && ($view['response']['kind'] ?? '') === 'photo'): ?>
<?php echo snap_render_html(snap_render_component('grid-photo-fragment', ['prefix' => 'tg', 'item' => $view['response']['item'] ?? [], 'photographs' => $view['response']['photographs'] ?? [], 'comments' => $view['response']['comments'] ?? [], 'site' => $view['site']])); ?>
<?php else: ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="sudden-impact-v2" data-carousel-indicator="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['carousel_indicator'] ?? ''); ?>" data-hover-overlay="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['hover_overlay'] ?? ''); ?>" data-nav-line-mode="<?php echo snap_escape_attr($view['site']['skin_presentation']['grid']['nav_line_mode'] ?? ''); ?>">
<?php if (!empty($view['site']['skin_presentation']['treatment']['enabled'])): ?><div class="tg-treatment-bg" aria-hidden="true"></div><div class="tg-treatment-overlay" aria-hidden="true"></div><?php endif; ?>
<div class="tg-content-wrap landing-feed">
<?php if (($view['site']['skin_presentation']['options']['tg_profile_header'] ?? '') === '1'): ?><section class="tg-profile">
<?php if (!empty($view['site']['avatar_url'])): ?><div class="tg-profile-avatar tg-profile-avatar--zoom"><img src="<?php echo snap_escape_url($view['site']['avatar_url']); ?>" alt="Profile avatar"></div><?php else: ?><div class="tg-profile-avatar"><span class="tg-profile-avatar-initials"><?php echo snap_escape_html($view['site']['site_name']); ?></span></div><?php endif; ?>
<div class="tg-profile-info"><div class="tg-profile-nameline"><h1 class="tg-profile-username"><?php echo snap_escape_html($view['site']['site_name']); ?></h1><?php if (($view['site']['skin_presentation']['options']['tg_show_tagline'] ?? '') === '1' && !empty($view['site']['tagline'])): ?><span class="tg-profile-tagline-sep">/</span><p class="tg-profile-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?></div>
<div class="tg-profile-stats"><div class="tg-profile-stat"><span class="tg-profile-stat-num"><?php echo snap_escape_html($view['response']['photo_count'] ?? ''); ?></span><span class="tg-profile-stat-label">posts</span></div></div><?php if (!empty($view['site']['site_description'])): ?><p class="tg-profile-bio"><?php echo snap_escape_html($view['site']['site_description']); ?></p><?php endif; ?></div></section><?php endif; ?>
<nav class="tg-sticky-nav" aria-label="Site navigation"><div class="tg-sticky-nav-inner"><ul class="tg-sticky-nav-links"><?php if (!empty($view['response']['navigation'])): ?><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation']])); ?><?php else: ?><li><a class="active" href="<?php echo snap_route_url('home'); ?>">Home</a></li><?php endif; ?></ul></div></nav>
<?php if (($view['response']['kind'] ?? '') === 'landing' || ($view['response']['kind'] ?? '') === 'archive' || ($view['response']['kind'] ?? '') === 'hashtag' || ($view['response']['kind'] ?? '') === 'photo'): ?><main><div id="browse-grid" class="tg-grid public-grid h-feed archive-grid">
<?php foreach (($view['response']['items'] ?? []) as $item): ?><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_thumb_square']) || !empty($item['img_file'])): ?><article class="tg-tile<?php if (!empty($item['is_framed'])): ?> tg-tile--framed<?php endif; ?>" style="<?php echo snap_escape_attr($item['frame_style'] ?? ''); ?>"><a href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo', ['slug' => $item['img_slug'] ?? ''])); ?>" title="<?php echo snap_escape_attr($item['img_title'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $item['img_thumb_aspect'] ?? $item['img_thumb_square'] ?? $item['img_file'], 'alt' => $item['img_alt'] ?? $item['img_title'] ?? ''])); ?></a></article><?php endif; ?><?php endforeach; ?></div></main>
<?php elseif (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post'): ?><main><article class="tg-post-ig"><div class="tg-post-ig-image">
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="tg-carousel-wrap"><div id="tg-carousel" class="ss-slider" data-slider-mode="carousel"><div class="slider-track"><?php foreach ($view['response']['photographs'] as $photograph): ?><div class="slider-slide<?php if (!empty($photograph['is_framed'])): ?> tg-slide--framed<?php endif; ?>" data-image-id="<?php echo snap_escape_attr($photograph['id'] ?? ''); ?>" style="<?php echo snap_escape_attr($photograph['frame_style'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $photograph['img_file'] ?? '', 'alt' => $photograph['img_alt'] ?? $photograph['img_title'] ?? '', 'attributes' => ['data-lightbox-src' => $photograph['img_file'] ?? '']])); ?></div><?php endforeach; ?></div></div></div>
<?php elseif (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'], 'alt' => $view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '', 'class' => 'tg-single-img'])); ?><?php endif; ?></div><div class="tg-post-ig-info"><div class="tg-post-ig-body"><h1><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? ''); ?></h1><div class="tg-post-caption-block"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div></div></div></article></main>
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><main><article class="tg-static-page"><h1 class="tg-static-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? ''); ?></h1><div class="tg-static-content"><?php echo snap_render_html($view['response']['item']['content'] ?? ''); ?></div></article></main>
<?php else: ?><main><section class="tg-grid-empty"><h1>Not found</h1></section></main><?php endif; ?>
<?php if (($view['response']['kind'] ?? '') === 'post' && !empty($view['response']['photographs'])): ?><div class="ss-slider-dots" data-slider-indicators><?php foreach ($view['response']['photographs'] as $slideIndex => $photograph): ?><button type="button" class="ss-slider-dot<?php if ($slideIndex === 0): ?> is-active<?php endif; ?>" data-slide-index="<?php echo snap_escape_attr($slideIndex); ?>" aria-label="<?php echo snap_escape_attr($photograph['img_title'] ?? 'Photograph'); ?>"></button><?php endforeach; ?></div><?php endif; ?>
<?php echo snap_render_html(snap_render_component('gram-search-dock', ['dock' => $view['site']['search_dock'] ?? []])); ?><footer id="system-footer" class="site-footer"><div id="footer"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div>
<div id="tg-modal-overlay" class="tg-modal-overlay" hidden data-grid-url="<?php echo snap_route_url('home'); ?>"<?php if (!empty($view['response']['autoopen'])): ?> data-autoopen="1"<?php endif; ?>><div class="tg-modal-backdrop"></div><div id="tg-modal-frame" class="tg-modal-frame"></div></div><div id="tg-lightbox" class="tg-lightbox" hidden><button type="button" class="tg-lightbox-close" aria-label="Close">&times;</button><img class="tg-lightbox-img" src="" alt=""></div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
<?php if (($view['response']['kind'] ?? '') === 'landing' && !empty($view['response']['next_page'])): ?><div id="tg-sentinel" class="ss-feed-sentinel" data-feed data-next="<?php echo snap_escape_attr($view['response']['next_page']); ?>" data-base="<?php echo snap_escape_url($view['site']['base_url']); ?>" aria-hidden="true"></div><?php endif; ?>
</body></html>
<?php endif; ?>
