<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?><?php echo snap_render_html($view['site']['skin_presentation']['style'] ?? ''); ?></head>
<body class="impact-printer-v2"><div id="page-wrapper"><div id="scroll-stage">
<header id="ip-header" class="site-header" data-sticky-header><div class="ip-header-inside"><a class="site-title logo-area" href="<?php echo snap_route_url('home'); ?>"><span class="site-title-text"><?php echo snap_escape_html($view['site']['site_name']); ?></span></a><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></div></header>
<?php if (($view['response']['kind'] ?? '') === 'photo' || ($view['response']['kind'] ?? '') === 'post' || ($view['response']['kind'] ?? '') === 'page' || ($view['response']['kind'] ?? '') === 'collection'): ?>
<main id="ip-photobox" class="h-entry single-image-page"><div class="ip-photo-wrap"><?php if (!empty($view['response']['item']['img_file']) || !empty($view['response']['item']['featured_image_path'])): ?><div class="ip-ascii-frame" data-border-style="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['image_frame_style'] ?? ''); ?>"><span class="ip-border-left"></span><div class="ip-ascii-frame-inner"><?php echo snap_render_html(snap_render_component('image', ['url'=>$view['response']['item']['img_file'] ?? $view['response']['item']['featured_image_path'],'alt'=>$view['response']['item']['img_alt'] ?? $view['response']['item']['img_title'] ?? '','class'=>'ip-image post-image','id'=>'main-image'])); ?></div><span class="ip-border-right"></span></div><?php endif; ?></div></main>
<div id="infobox"><?php echo snap_render_html(snap_render_component('navigation', ['items'=>$view['response']['navigation'] ?? []])); ?></div>
<div id="footer"><section id="pane-info" class="footer-pane"><h1 class="p-name photo-title-footer"><?php echo snap_escape_html($view['response']['item']['img_title'] ?? $view['response']['item']['title'] ?? $view['response']['item']['name'] ?? ''); ?></h1><?php if (!empty($view['response']['item']['img_date']) || !empty($view['response']['item']['created_at'])): ?><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?>"><?php echo snap_escape_html($view['response']['item']['img_date'] ?? $view['response']['item']['created_at']); ?></time><?php endif; ?><div class="description entry-content e-content static-transmission"><?php echo snap_render_html($view['response']['item']['content'] ?? $view['response']['item']['description'] ?? $view['response']['item']['img_description'] ?? ''); ?></div><?php if (!empty($view['response']['item']['exif'])): ?><div class="meta"><div class="meta-header">TECHNICAL SPECIFICATIONS</div><table class="exif-table"><?php foreach ($view['response']['item']['exif'] as $label=>$value): ?><tr><td class="exif-label"><?php echo snap_escape_html($label); ?></td><td class="exif-value"><?php echo snap_escape_html($value); ?></td></tr><?php endforeach; ?></table></div><?php endif; ?></section><section id="pane-comments" class="footer-pane"><?php echo snap_render_html(snap_render_component('comments', ['items'=>$view['response']['comments'] ?? []])); ?></section></div>
<?php elseif (($view['response']['kind'] ?? '') === 'search'): ?><main class="static-content search-results"><h1 class="static-page-title"><?php echo snap_escape_html($view['response']['page_title'] ?? 'Search'); ?></h1><?php foreach (($view['response']['results'] ?? []) as $group): ?><?php foreach ($group as $item): ?><article><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? ''); ?></h2></article><?php endforeach; ?><?php endforeach; ?></main>
<?php else: ?><main id="browse-grid" class="public-grid archive-grid"><?php foreach (($view['response']['items'] ?? []) as $item): ?><article class="thumb-container"><a class="thumb-link" href="<?php echo snap_escape_url($item['url'] ?? snap_route_url('photo',['slug'=>$item['img_slug'] ?? ''])); ?>"><?php if (!empty($item['img_thumb_aspect']) || !empty($item['img_file'])): ?><div class="ip-ascii-frame snap-inline-frame" data-border-style="<?php echo snap_escape_attr($view['site']['skin_presentation']['options']['inline_frame_style'] ?? ''); ?>"><span class="ip-border-left"></span><div class="ip-ascii-frame-inner"><?php echo snap_render_html(snap_render_component('image',['url'=>$item['img_thumb_aspect'] ?? $item['img_file'],'alt'=>$item['img_alt'] ?? $item['img_title'] ?? ''])); ?></div><span class="ip-border-right"></span></div><?php endif; ?><h2><?php echo snap_escape_html($item['img_title'] ?? $item['title'] ?? $item['name'] ?? ''); ?></h2></a></article><?php endforeach; ?></main><?php endif; ?>
<footer id="system-footer" class="site-footer"><div class="inside"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div></div><?php echo snap_render_html(snap_render_component('registered-assets',['assets'=>$view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?></body></html>
