<?php
// Generated by tools/_build/generate-skin-visibility-baseline.php. Shrink only.
return array (
  'alfred' =>
  array (
    'preload.php' =>
    array (
      0 =>
      array (
        'file' => 'preload.php',
        'line' => 57,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'preload.php',
        'line' => 167,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      2 =>
      array (
        'file' => 'preload.php',
        'line' => 185,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      3 =>
      array (
        'file' => 'preload.php',
        'line' => 185,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      4 =>
      array (
        'file' => 'preload.php',
        'line' => 194,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      5 =>
      array (
        'file' => 'preload.php',
        'line' => 194,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      6 =>
      array (
        'file' => 'preload.php',
        'line' => 226,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      7 =>
      array (
        'file' => 'preload.php',
        'line' => 234,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      8 =>
      array (
        'file' => 'preload.php',
        'line' => 359,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      9 =>
      array (
        'file' => 'preload.php',
        'line' => 364,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      10 =>
      array (
        'file' => 'preload.php',
        'line' => 364,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'aurora' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 89,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'game-on' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 96,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'landing.php',
        'line' => 184,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'puzzle-field.php' =>
    array (
      0 =>
      array (
        'file' => 'puzzle-field.php',
        'line' => 26,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'heuristic' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 89,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'landing.php',
        'line' => 162,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'instant-camera' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 70,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 70,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 95,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'jive-turkey' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 89,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'parade' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 89,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'photogram' =>
  array (
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 84,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 44,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 50,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'scroll' =>
  array (
    'nav-filter.php' =>
    array (
      0 =>
      array (
        'file' => 'nav-filter.php',
        'line' => 28,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'nav-filter.php',
        'line' => 33,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
    'wall.php' =>
    array (
      0 =>
      array (
        'file' => 'wall.php',
        'line' => 205,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'wall.php',
        'line' => 206,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
  ),
  'slickr' =>
  array (
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 70,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
    'skin-header.php' =>
    array (
      0 =>
      array (
        'file' => 'skin-header.php',
        'line' => 77,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'skin-header.php',
        'line' => 96,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      2 =>
      array (
        'file' => 'skin-header.php',
        'line' => 109,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
  ),
  'sliders' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 70,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 70,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 88,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'stanley' =>
  array (
    'preload.php' =>
    array (
      0 =>
      array (
        'file' => 'preload.php',
        'line' => 45,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'preload.php',
        'line' => 45,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      2 =>
      array (
        'file' => 'preload.php',
        'line' => 140,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      3 =>
      array (
        'file' => 'preload.php',
        'line' => 154,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      4 =>
      array (
        'file' => 'preload.php',
        'line' => 154,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      5 =>
      array (
        'file' => 'preload.php',
        'line' => 161,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      6 =>
      array (
        'file' => 'preload.php',
        'line' => 161,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      7 =>
      array (
        'file' => 'preload.php',
        'line' => 187,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      8 =>
      array (
        'file' => 'preload.php',
        'line' => 190,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      9 =>
      array (
        'file' => 'preload.php',
        'line' => 280,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      10 =>
      array (
        'file' => 'preload.php',
        'line' => 282,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      11 =>
      array (
        'file' => 'preload.php',
        'line' => 282,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'skin-footer.php' =>
    array (
      0 =>
      array (
        'file' => 'skin-footer.php',
        'line' => 22,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
  ),
  'sudden-impact' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 96,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'telegram' =>
  array (
    'preload.php' =>
    array (
      0 =>
      array (
        'file' => 'preload.php',
        'line' => 57,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'preload.php',
        'line' => 167,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      2 =>
      array (
        'file' => 'preload.php',
        'line' => 185,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      3 =>
      array (
        'file' => 'preload.php',
        'line' => 185,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      4 =>
      array (
        'file' => 'preload.php',
        'line' => 194,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      5 =>
      array (
        'file' => 'preload.php',
        'line' => 194,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      6 =>
      array (
        'file' => 'preload.php',
        'line' => 226,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      7 =>
      array (
        'file' => 'preload.php',
        'line' => 234,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      8 =>
      array (
        'file' => 'preload.php',
        'line' => 346,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      9 =>
      array (
        'file' => 'preload.php',
        'line' => 351,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      10 =>
      array (
        'file' => 'preload.php',
        'line' => 351,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'the-grid' =>
  array (
    'archive-layout.php' =>
    array (
      0 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'archive-layout.php',
        'line' => 65,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'hashtag.php' =>
    array (
      0 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'hashtag.php',
        'line' => 69,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'landing.php' =>
    array (
      0 =>
      array (
        'file' => 'landing.php',
        'line' => 96,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'layout.php' =>
    array (
      0 =>
      array (
        'file' => 'layout.php',
        'line' => 42,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'layout.php',
        'line' => 49,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
  ),
  'writing-with-impact' =>
  array (
    'preload.php' =>
    array (
      0 =>
      array (
        'file' => 'preload.php',
        'line' => 35,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      1 =>
      array (
        'file' => 'preload.php',
        'line' => 35,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      2 =>
      array (
        'file' => 'preload.php',
        'line' => 124,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      3 =>
      array (
        'file' => 'preload.php',
        'line' => 138,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      4 =>
      array (
        'file' => 'preload.php',
        'line' => 138,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      5 =>
      array (
        'file' => 'preload.php',
        'line' => 145,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      6 =>
      array (
        'file' => 'preload.php',
        'line' => 145,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
      7 =>
      array (
        'file' => 'preload.php',
        'line' => 171,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      8 =>
      array (
        'file' => 'preload.php',
        'line' => 174,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      9 =>
      array (
        'file' => 'preload.php',
        'line' => 264,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      10 =>
      array (
        'file' => 'preload.php',
        'line' => 266,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
      11 =>
      array (
        'file' => 'preload.php',
        'line' => 266,
        'type' => 'image',
        'missing' =>
        array (
          0 => 'publication-state',
          1 => 'publication-time',
        ),
      ),
    ),
    'skin-footer.php' =>
    array (
      0 =>
      array (
        'file' => 'skin-footer.php',
        'line' => 21,
        'type' => 'post',
        'missing' =>
        array (
          0 => 'publication-time',
        ),
      ),
    ),
  ),
);
