<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html>
<html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title>
<?php if (!empty($view['site']['favicon_url'])): ?><link rel="icon" href="<?php echo snap_escape_url($view['site']['favicon_url']); ?>"><?php endif; ?>
<link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>">
<?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?>
</head>
<?php if (($view['response']['kind'] ?? '') === 'feed'): ?><body class="blog<?php if (!empty($view['response']['show_titles'])): ?> show-preview-titles<?php endif; ?> tilez-v2">
<?php elseif (($view['response']['kind'] ?? '') === 'archive'): ?><body class="archive alfred-archive tilez-v2">
<?php elseif (($view['response']['kind'] ?? '') === 'single'): ?><body class="single tilez-v2">
<?php elseif (($view['response']['kind'] ?? '') === 'blogroll'): ?><body class="blogroll tilez-v2">
<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?><body class="page tilez-page-view tilez-v2">
<?php elseif (($view['response']['kind'] ?? '') === 'taxonomy'): ?><body class="archive tilez-taxonomy tilez-v2">
<?php else: ?><body class="not-found tilez-v2"><?php endif; ?>
<div id="page" class="tilez">
<header id="header" class="site-header header section-inner" data-sticky-header="false"><div class="inside">
<a class="custom-logo-link blog-logo" href="<?php echo snap_route_url('home'); ?>"><?php if (!empty($view['site']['skin_presentation']['header_media']['logo'])): ?><img class="custom-logo<?php if (!empty($view['site']['skin_presentation']['header_media']['retina'])): ?> site-logo-retina<?php endif; ?>" src="<?php echo snap_escape_url($view['site']['skin_presentation']['header_media']['logo']); ?>" alt="<?php echo snap_escape_attr($view['site']['site_name']); ?>"><?php else: ?><span class="site-title-text"><?php echo snap_escape_html($view['site']['site_name']); ?></span><?php endif; ?></a>
<?php if (!empty($view['site']['skin_presentation']['header_media']['show_tagline']) && !empty($view['site']['tagline'])): ?><p class="site-tagline blog-description"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?>
</div></header>
<nav class="navigation" aria-label="Primary"><div class="section-inner">
<ul class="main-menu"><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation'] ?? []])); ?></ul>
<div class="tilez-icon-nav" aria-label="Quick navigation">
<a href="<?php echo snap_route_url('home'); ?>" aria-label="Home"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5v8a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/></svg></a>
<a href="<?php echo snap_route_url('page', ['slug' => 'about']); ?>" aria-label="About"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><line x1="12" y1="11" x2="12" y2="16.5"/><circle cx="12" cy="7.8" r="1.05" fill="currentColor"/></svg></a>
<a href="<?php echo snap_route_url('blogroll'); ?>" aria-label="Blogroll"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="6" r="1.5" fill="currentColor"/><circle cx="5" cy="12" r="1.5" fill="currentColor"/><circle cx="5" cy="18" r="1.5" fill="currentColor"/><path d="M9 6h11M9 12h11M9 18h11"/></svg></a>
<details class="tilez-nav-search"><summary aria-label="Search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg></summary><form class="tilez-nav-search-panel" method="get" action="<?php echo snap_route_url('archive'); ?>"><label class="screen-reader-text" for="tilez-nav-search-input">Search photographs</label><input id="tilez-nav-search-input" type="search" name="q" placeholder="Search or #tag…" autocomplete="off"><button type="submit">GO</button></form></details>
</div>
<button class="nav-toggle" type="button" aria-label="Toggle navigation"><span class="bars"><span class="bar"></span><span class="bar"></span><span class="bar"></span></span></button>
<div class="mobile-navigation"><ul class="mobile-menu"><?php echo snap_render_html(snap_render_component('navigation-tree', ['items' => $view['response']['navigation'] ?? []])); ?></ul></div>
</div></nav>
<div class="header-image" aria-hidden="true"><?php if (!empty($view['site']['skin_presentation']['header_media']['image'])): ?><img class="header-media-image" src="<?php echo snap_escape_url($view['site']['skin_presentation']['header_media']['image']); ?>" alt=""><?php endif; ?></div>

<?php if (($view['response']['kind'] ?? '') === 'single'): ?>
<main class="content" role="main"><article class="smacktalk-post post-container h-entry"><div class="post-inner">
<div class="post-content entry-content e-content" data-merge-adjacent-mosaics><?php echo snap_render_html($view['response']['rendered_content'] ?? ''); ?><?php if (!empty($view['response']['signature']['url'])): ?><div class="post-signature post-signature--closing"><img src="<?php echo snap_escape_url($view['response']['signature']['url']); ?>" alt="<?php echo snap_escape_attr($view['response']['signature']['alt'] ?? ''); ?>"></div><?php endif; ?></div>
<aside class="post-record" aria-label="Post details"><div class="post-header"><h1 class="post-title p-name"><?php echo snap_escape_html($view['response']['post']['title'] ?? ''); ?></h1><p class="post-date"><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['post']['created_at'] ?? ''); ?>"><?php echo snap_escape_html($view['response']['post']['created_at'] ?? ''); ?></time></p></div>
<dl class="post-facts"><div><dt>Photos</dt><dd><?php echo snap_escape_html($view['response']['photo_count'] ?? 0); ?></dd></div><div><dt>Words</dt><dd><?php echo snap_escape_html($view['response']['word_count'] ?? 0); ?></dd></div><?php if (!empty($view['response']['categories_label'])): ?><div><dt>Category</dt><dd><?php echo snap_escape_html($view['response']['categories_label']); ?></dd></div><?php endif; ?><?php if (!empty($view['response']['albums_label'])): ?><div><dt>Album</dt><dd><?php echo snap_escape_html($view['response']['albums_label']); ?></dd></div><?php endif; ?><?php if (!empty($view['response']['author'])): ?><div><dt>Author</dt><dd class="p-author"><?php echo snap_escape_html($view['response']['author']); ?></dd></div><?php endif; ?></dl>
<?php if (!empty($view['response']['colophon'])): ?><div class="post-record-gear"><h2>Colophon</h2><p><?php echo snap_escape_html($view['response']['colophon']); ?></p></div><?php endif; ?></aside>
<?php if (!empty($view['response']['colophon'])): ?><div class="post-mobile-gear"><h2>Colophon</h2><p><?php echo snap_escape_html($view['response']['colophon']); ?></p></div><?php endif; ?>
</div></article>
<?php if (!empty($view['response']['next']) || !empty($view['response']['previous'])): ?><nav class="post-navigation" aria-label="Post navigation"><?php if (!empty($view['response']['next']['url'])): ?><a href="<?php echo snap_escape_url($view['response']['next']['url']); ?>" class="post-nav-next"><span class="fa">‹</span><p><?php echo snap_escape_html($view['response']['next']['title'] ?? ''); ?></p></a><?php endif; ?><?php if (!empty($view['response']['previous']['url'])): ?><a href="<?php echo snap_escape_url($view['response']['previous']['url']); ?>" class="post-nav-prev"><p><?php echo snap_escape_html($view['response']['previous']['title'] ?? ''); ?></p><span class="fa">›</span></a><?php endif; ?></nav><?php endif; ?>
<?php if (!empty($view['response']['comments_enabled'])): ?><div class="comments-container"><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments'] ?? []])); ?></div><?php endif; ?></main>

<?php elseif (($view['response']['kind'] ?? '') === 'page'): ?>
<main class="content tilez-page" role="main"><article class="page-container post-inner"><div class="page-content post-content entry-content"><?php echo snap_render_html($view['response']['rendered_content'] ?? ''); ?></div><aside class="page-record post-record" aria-label="Page details"><header class="post-header"><h1 class="post-title"><?php echo snap_escape_html($view['response']['item']['title'] ?? $view['response']['page_title'] ?? ''); ?></h1></header></aside></article></main>

<?php elseif (($view['response']['kind'] ?? '') === 'feed'): ?>
<main class="content" role="main"><section class="section-inner"><div id="browse-grid" class="posts ss-masonry tilez-posts smacktalk-feed public-grid h-feed"><?php foreach (($view['response']['posts'] ?? []) as $post): ?><a class="post<?php if (!empty($post['image_url'])): ?> has-post-thumbnail<?php endif; ?> ss-masonry-item smacktalk-feed-item h-entry" href="<?php echo snap_escape_url($post['url'] ?? ''); ?>" data-w="<?php echo snap_escape_attr($post['width'] ?? 3); ?>" data-h="<?php echo snap_escape_attr($post['height'] ?? 2); ?>" aria-label="<?php echo snap_escape_attr($post['title'] ?? ''); ?>"><?php if (!empty($post['image_url'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $post['image_url'], 'alt' => $post['title'] ?? ''])); ?><?php endif; ?><span class="post-overlay"><span class="archive-post-header"><span class="archive-post-date"><?php echo snap_escape_html($post['created_label'] ?? $post['created_at'] ?? ''); ?></span><span class="archive-post-title p-name"><?php echo snap_escape_html($post['title'] ?? ''); ?></span></span></span></a><?php endforeach; ?></div>
<?php if (($view['response']['total_pages'] ?? 1) > 1): ?><nav class="archive-nav" aria-label="Page navigation"><span class="sep"><?php echo snap_escape_html($view['response']['page'] ?? 1); ?> / <?php echo snap_escape_html($view['response']['total_pages']); ?></span></nav><?php endif; ?></section></main>

<?php elseif (($view['response']['kind'] ?? '') === 'archive'): ?>
<main class="content" role="main"><section class="section-inner"><div class="alfred-archive-grid ss-masonry"><?php foreach (($view['response']['tiles'] ?? []) as $tile): ?><a class="alfred-archive-tile ss-masonry-item" href="<?php echo snap_escape_url($tile['full'] ?? ''); ?>" data-full="<?php echo snap_escape_attr($tile['full'] ?? ''); ?>" data-title="<?php echo snap_escape_attr($tile['title'] ?? ''); ?>" data-w="<?php echo snap_escape_attr($tile['width'] ?? 3); ?>" data-h="<?php echo snap_escape_attr($tile['height'] ?? 2); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $tile['thumb'] ?? '', 'alt' => $tile['title'] ?? ''])); ?></a><?php endforeach; ?></div></section></main>
<div id="alfred-archive-lightbox" class="alfred-lightbox" hidden aria-hidden="true" role="dialog" aria-modal="true" aria-label="Photograph viewer"><button type="button" class="alfred-lb-close" aria-label="Close">✕</button><button type="button" class="alfred-lb-prev" aria-label="Previous photograph">‹</button><img class="alfred-lb-img" src="" alt=""><button type="button" class="alfred-lb-next" aria-label="Next photograph">›</button><p class="alfred-lb-caption"></p></div>
<?php elseif (($view['response']['kind'] ?? '') === 'taxonomy'): ?>
<main class="content tilez-taxonomy-page" role="main"><section class="section-inner"><header class="taxonomy-heading"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? ''); ?></h1></header><div class="taxonomy-grid"><?php foreach (($view['response']['groups'] ?? []) as $group): ?><a class="taxonomy-card" href="<?php echo snap_escape_url($group['url'] ?? ''); ?>"><?php if (!empty($group['cover_url'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $group['cover_url'], 'alt' => $group['label'] ?? ''])); ?><?php endif; ?><span class="taxonomy-card-copy"><strong><?php echo snap_escape_html($group['label'] ?? ''); ?></strong><small><?php echo snap_escape_html($group['photograph_count'] ?? 0); ?> photographs</small><?php if (!empty($group['description'])): ?><span><?php echo snap_escape_html($group['description']); ?></span><?php endif; ?></span></a><?php endforeach; ?></div></section></main>
<?php elseif (($view['response']['kind'] ?? '') === 'blogroll'): ?>
<main class="content tilez-blogroll" role="main"><section class="section-inner"><header class="blogroll-heading"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? 'BLOGROLL'); ?></h1></header><div class="blogroll-grid"><?php foreach (($view['response']['blogroll_groups'] ?? []) as $group): ?><section class="blogroll-group"><h2><?php echo snap_escape_html($group['label'] ?? ''); ?></h2><ul><?php foreach (($group['items'] ?? []) as $peer): ?><li><a href="<?php echo snap_escape_url($peer['url'] ?? ''); ?>" target="_blank" rel="noopener noreferrer"><?php echo snap_escape_html($peer['name'] ?? ''); ?></a><?php if (!empty($peer['description'])): ?><p><?php echo snap_escape_html($peer['description']); ?></p><?php endif; ?></li><?php endforeach; ?></ul></section><?php endforeach; ?></div></section></main>
<?php else: ?><main class="content not-found" role="main"><section class="section-inner"><h1>Not found</h1><p><a href="<?php echo snap_route_url('home'); ?>">Back to the front</a></p></section></main><?php endif; ?>

<footer id="system-footer" class="site-footer<?php if (!empty($view['site']['footer']['lowercase'])): ?> footer-lowercase<?php endif; ?>"><div id="footer" class="inside"><?php echo snap_render_html(snap_render_component('footer', ['footer' => $view['site']['footer'] ?? []])); ?></div></footer>
</div>
<?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?>
<?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?>
</body></html>
