<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/core/public-visibility.php';
$root = dirname(__DIR__, 2);
$result = [];
foreach (glob($root . '/skins/*/manifest.json') ?: [] as $manifest) {
    $dir = dirname($manifest);
    $slug = basename($dir);
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS));
    foreach ($it as $file) {
        if (!$file->isFile() || strtolower($file->getExtension()) !== 'php') continue;
        $rel = str_replace('\\', '/', substr($file->getPathname(), strlen($dir) + 1));
        $findings = snapsmack_skin_visibility_query_findings($file->getPathname(), $rel);
        if ($findings) $result[$slug][$rel] = $findings;
    }
}
ksort($result);
$export = preg_replace('/[ \t]+$/m', '', var_export($result, true));
$out = "<?php\n// Generated by tools/_build/generate-skin-visibility-baseline.php. Shrink only.\nreturn "
    . $export . ";\n";
file_put_contents($root . '/core/skin-visibility-legacy.php', $out);
echo 'Recorded ' . array_sum(array_map(static fn(array $files): int => array_sum(array_map('count', $files)), $result)) . " visibility query finding(s).\n";
