<?php
declare(strict_types=1);

$root = dirname(__DIR__, 2);
$profiles = [
    'alfred' => ['page'=>'page','header'=>'header','content'=>'content','feed'=>'posts ss-masonry tilez-posts','item'=>'post','archive'=>'alfred-archive-grid','footer'=>'system-footer'],
    'tilez' => ['page'=>'page','header'=>'header','content'=>'content','feed'=>'posts ss-masonry tilez-posts','item'=>'post','archive'=>'alfred-archive-grid','footer'=>'system-footer'],
    'stanley' => ['page'=>'stanley-page','header'=>'stanley-header','content'=>'stanley-content','feed'=>'stanley-posts','item'=>'stanley-post-summary','archive'=>'stanley-archive-grid','footer'=>'stanley-footer'],
    'writing-with-impact' => ['page'=>'wwi-page','header'=>'wwi-header','content'=>'wwi-content','feed'=>'wwi-posts','item'=>'wwi-post-summary','archive'=>'wwi-archive-grid','footer'=>'wwi-skin-footer'],
];
$template = <<<'PHP'
<?php defined('SNAPSMACK_SKIN_RENDER') || exit; ?>
<!doctype html><html lang="<?php echo snap_escape_attr($view['site']['language']); ?>" dir="<?php echo snap_escape_attr($view['site']['direction']); ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo snap_escape_html($view['response']['page_title'] ?? $view['site']['site_name']); ?></title><link rel="stylesheet" href="<?php echo snap_escape_url($view['site']['skin_style_url']); ?>"><?php echo snap_render_html($view['site']['skin_custom_style'] ?? ''); ?></head>
<body class="{{SLUG}}-v2"><div id="{{PAGE}}" class="{{SLUG}}"><header id="{{HEADER}}" class="site-header header section-inner" data-sticky-header="false"><div class="inside"><a class="site-title logo-area blog-title" href="<?php echo snap_route_url('home'); ?>"><span class="site-title-text"><?php echo snap_escape_html($view['site']['site_name']); ?></span></a><?php if (!empty($view['site']['tagline'])): ?><p class="site-tagline"><?php echo snap_escape_html($view['site']['tagline']); ?></p><?php endif; ?><?php echo snap_render_html(snap_render_component('navigation', ['items' => $view['response']['navigation'] ?? []])); ?></div></header>
<div id="{{CONTENT}}"><main id="scroll-stage" class="content post-inner reading-column longform" role="main">
<?php if (($view['response']['kind'] ?? '') === 'single'): ?><article class="smacktalk-post post-container h-entry"><div class="post-header"><h1 class="post-title p-name"><?php echo snap_escape_html($view['response']['post']['title'] ?? ''); ?></h1><p class="post-date"><?php echo snap_escape_html($view['response']['post']['created_at'] ?? ''); ?></p><?php if (!empty($view['response']['post']['created_at'])): ?><time class="dt-published" datetime="<?php echo snap_escape_attr($view['response']['post']['created_at']); ?>"></time><?php endif; ?><?php if (!empty($view['site']['owner_name'])): ?><span class="p-author h-card"><span class="p-name"><?php echo snap_escape_html($view['site']['owner_name']); ?></span></span><?php endif; ?></div><div class="post-inner"><?php if (!empty($view['response']['post']['featured_image_path'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $view['response']['post']['featured_image_path'], 'alt' => $view['response']['post']['title'] ?? ''])); ?><?php endif; ?><div class="post-content entry-content e-content"><?php echo snap_render_html($view['response']['rendered_content'] ?? ''); ?></div><?php if (!empty($view['response']['colophon'])): ?><aside class="post-colophon"><?php echo snap_escape_html($view['response']['colophon']); ?></aside><?php endif; ?><?php if (!empty($view['response']['comments_enabled'])): ?><?php echo snap_render_html(snap_render_component('comments', ['items' => $view['response']['comments'] ?? []])); ?><?php endif; ?></div></article>
<?php elseif (($view['response']['kind'] ?? '') === 'feed'): ?><section class="section-inner"><div id="browse-grid" class="{{FEED}} smacktalk-feed public-grid h-feed"><?php foreach (($view['response']['posts'] ?? []) as $post): ?><article class="{{ITEM}} smacktalk-feed-item"><a href="<?php echo snap_escape_url($post['url'] ?? ''); ?>"><?php if (!empty($post['image_url'])): ?><?php echo snap_render_html(snap_render_component('image', ['url' => $post['image_url'], 'alt' => $post['title'] ?? ''])); ?><?php endif; ?><h2><?php echo snap_escape_html($post['title'] ?? ''); ?></h2></a></article><?php endforeach; ?></div></section>
<?php elseif (($view['response']['kind'] ?? '') === 'archive'): ?><section class="section-inner smacktalk-archive"><h1><?php echo snap_escape_html($view['response']['page_title'] ?? 'Archive'); ?></h1><div class="{{ARCHIVE}}"><?php foreach (($view['response']['tiles'] ?? []) as $tile): ?><a href="<?php echo snap_escape_url($tile['full'] ?? ''); ?>"><?php echo snap_render_html(snap_render_component('image', ['url' => $tile['thumb'] ?? '', 'alt' => $tile['title'] ?? ''])); ?></a><?php endforeach; ?></div></section>
<?php else: ?><section class="not-found"><h1>Not found</h1></section><?php endif; ?>
</main></div><footer id="{{FOOTER}}" class="site-footer"><div id="footer" class="inside"><p id="sig-text"><?php echo snap_escape_html($view['site']['site_name']); ?></p></div></footer></div><?php echo snap_render_html(snap_render_component('registered-assets', ['assets' => $view['site']['registered_assets'] ?? []])); ?><?php echo snap_render_html($view['site']['owner_custom_code'] ?? ''); ?></body></html>
PHP;

foreach ($profiles as $slug => $profile) {
    $replace = ['{{SLUG}}'=>$slug,'{{PAGE}}'=>$profile['page'],'{{HEADER}}'=>$profile['header'],'{{CONTENT}}'=>$profile['content'],'{{FEED}}'=>$profile['feed'],'{{ITEM}}'=>$profile['item'],'{{ARCHIVE}}'=>$profile['archive'],'{{FOOTER}}'=>$profile['footer']];
    file_put_contents($root . '/skins/' . $slug . '/layout.php', strtr($template, $replace) . "\n");
}
echo 'Restored layout ownership for ' . count($profiles) . " SMACKTALK skins.\n";
