"""Curated first-party LEWKS shipped with SNAP SLAPPER."""

# SNAPSMACK_EOF_HEADER

import copy
import time

from editor_engine import DEFAULT_ADJUSTMENTS, PROJECT_VERSION


LEWKS = (
    {"id": "clean-slate", "name": "CLEAN SLATE", "category": "Clean + Corrective",
     "description": "Quiet contrast, open shadows, restrained colour. A clean starting point.",
     "adjustments": {"exposure": .10, "contrast": 8, "highlights": -18, "shadows": 16,
                     "whites": 6, "blacks": -5, "vibrance": 8, "clarity": 5, "sharpen": 12}},
    {"id": "golden-hourglass", "name": "GOLDEN HOURGLASS", "category": "Landscape + Weather",
     "description": "Warm late light, protected highlights, and a little prairie glow.",
     "adjustments": {"temperature": 24, "tint": 3, "highlights": -30, "shadows": 12,
                     "vibrance": 18, "clarity": 7, "vignette": -10,
                     "curve": [[0, 8], [55, 48], [132, 142], [210, 226], [255, 250]]}},
    {"id": "frost-warning", "name": "FROST WARNING", "category": "Landscape + Weather",
     "description": "Cold air, pale colour, crystalline edges, and winter restraint.",
     "adjustments": {"temperature": -26, "tint": -3, "saturation": -14, "vibrance": 8,
                     "highlights": -12, "whites": 15, "texture": 14, "sharpen": 16}},
    {"id": "parking-lot-disco", "name": "PARKING LOT DISCO", "category": "Night + Neon",
     "description": "Electric colour, deep blacks, neon punch, and after-midnight grain.",
     "adjustments": {"contrast": 22, "highlights": -20, "shadows": 10, "blacks": -20,
                     "saturation": 10, "vibrance": 34, "clarity": 12, "dehaze": 9,
                     "grain": 16, "vignette": -18}},
    {"id": "cheap-motel-cyan", "name": "CHEAP MOTEL CYAN", "category": "Night + Neon",
     "description": "Cool fluorescent colour, hard contrast, and beautifully questionable decisions.",
     "adjustments": {"temperature": -18, "tint": -12, "contrast": 28, "highlights": -25,
                     "shadows": -8, "saturation": -4, "vibrance": 24, "grain": 20,
                     "curve": [[0, 5], [48, 35], [128, 130], [205, 225], [255, 252]]}},
    {"id": "prairie-gothic", "name": "PRAIRIE GOTHIC", "category": "Film + Print",
     "description": "Storm-heavy skies, muted land, lifted black point, and rural menace.",
     "adjustments": {"exposure": -.08, "temperature": -6, "contrast": 14, "highlights": -38,
                     "shadows": -6, "saturation": -20, "clarity": 18, "dehaze": 16,
                     "grain": 18, "vignette": -22, "curve": [[0, 16], [64, 54], [150, 145], [255, 244]]}},
    {"id": "expired-in-alberta", "name": "EXPIRED IN ALBERTA", "category": "Film + Print",
     "description": "Faded drugstore colour, warm dust, soft contrast, and honest grain.",
     "adjustments": {"temperature": 13, "tint": 7, "contrast": -14, "highlights": -12,
                     "shadows": 20, "saturation": -12, "vibrance": 6, "texture": -5,
                     "grain": 26, "curve": [[0, 21], [64, 68], [150, 152], [255, 239]]}},
    {"id": "high-noon-hangover", "name": "HIGH NOON HANGOVER", "category": "Film + Print",
     "description": "Bleached sun, warm whites, blunt contrast, and yesterday's grain.",
     "adjustments": {"exposure": .12, "temperature": 17, "contrast": 18, "highlights": -10,
                     "shadows": -14, "whites": 22, "saturation": -10, "grain": 22,
                     "vignette": -8}},
    {"id": "silver-teeth", "name": "SILVER TEETH", "category": "Black + White",
     "description": "Bright metallic monochrome with crisp texture and disciplined blacks.",
     "adjustments": {"black_white": True, "contrast": 24, "highlights": -20, "shadows": 12,
                     "whites": 18, "blacks": -16, "clarity": 18, "texture": 12,
                     "sharpen": 15, "grain": 8}},
    {"id": "noir-means-noir", "name": "NOIR MEANS NOIR", "category": "Black + White",
     "description": "Deep cinematic monochrome, crushed edges, smoke, and consequence.",
     "adjustments": {"black_white": True, "exposure": -.18, "contrast": 38,
                     "highlights": -34, "shadows": -24, "blacks": -30, "clarity": 10,
                     "grain": 20, "vignette": -30}},
    {"id": "good-skin-bad-alibi", "name": "GOOD SKIN, BAD ALIBI", "category": "Portrait",
     "description": "Gentle skin, open shadows, warm colour, and eyes that still have something to hide.",
     "adjustments": {"temperature": 9, "tint": 5, "contrast": -6, "highlights": -22,
                     "shadows": 22, "vibrance": 9, "texture": -12, "clarity": -5,
                     "sharpen": 7, "vignette": -8}},
    {"id": "gasoline-rainbow", "name": "GASOLINE RAINBOW", "category": "Experimental",
     "description": "Aggressive colour separation, oily saturation, and unapologetic contrast.",
     "adjustments": {"tint": 18, "contrast": 30, "highlights": -28, "shadows": 8,
                     "saturation": 22, "vibrance": 38, "clarity": 16, "dehaze": 12,
                     "vignette": -14, "curve": [[0, 4], [45, 28], [120, 135], [210, 235], [255, 255]]}},

    # ── Looks drawn from the classic mobile-filter canon. The NAMES are ours;
    #    each recipe was rebuilt from scratch on SNAP SLAPPER's own primitives
    #    (curves, HSL, split-tone, photo filter, glow, grain) — glass-box, not
    #    baked LUTs, so every one opens up and tunes. ──
    {"id": "soft-spoken", "name": "SOFT SPOKEN", "category": "Portrait",
     "description": "Lifted blacks, rolled highlights, and a peach-and-blue pastel hush.",
     "adjustments": {"blacks": 14, "highlights": -20, "contrast": -8, "saturation": -18,
                     "vibrance": 6, "split_shadow": [95, 120, 170], "split_shadow_amount": 20,
                     "split_highlight": [255, 205, 175], "split_highlight_amount": 22}},
    {"id": "morning-afterglow", "name": "MORNING AFTERGLOW", "category": "Film + Print",
     "description": "Raised midtones, open blacks, a cool bias up top, and a warm centre bloom.",
     "adjustments": {"exposure": .10, "blacks": 10, "contrast": -4,
                     "split_highlight": [185, 220, 230], "split_highlight_amount": 12,
                     "glow_amount": 22, "glow_colour": [255, 238, 208], "glow_size": 55}},
    {"id": "brass-section", "name": "BRASS SECTION", "category": "Film + Print",
     "description": "A golden-yellow wash over low contrast and charcoal-lifted darks.",
     "adjustments": {"photo_filter_color": [235, 180, 60], "photo_filter_density": 22,
                     "contrast": -12, "blacks": 14, "highlights": -14,
                     "col_sat_orange": 12, "col_sat_yellow": 10, "col_sat_blue": -10}},
    {"id": "copper-kettle", "name": "COPPER KETTLE", "category": "Film + Print",
     "description": "High-contrast metallic sheen, sepia shadows, and a dark pull to the edges.",
     "adjustments": {"contrast": 26, "photo_filter_color": [172, 122, 51], "photo_filter_density": 12,
                     "split_shadow": [120, 90, 60], "split_shadow_amount": 28, "vignette": -26,
                     "curve": [[0, 6], [60, 48], [140, 150], [255, 250]]}},
    {"id": "stoop-life", "name": "STOOP LIFE", "category": "Clean + Corrective",
     "description": "Punchy midtones, a faint cyan in the shadows, and a brighter middle.",
     "adjustments": {"contrast": 12, "split_shadow": [120, 170, 180], "split_shadow_amount": 16,
                     "glow_amount": 14, "glow_colour": [245, 245, 235], "glow_size": 60}},
    {"id": "top-shelf", "name": "TOP SHELF", "category": "Film + Print",
     "description": "Rich saturation, amber shadows, cool highlights, and crisp edges.",
     "adjustments": {"saturation": 10, "contrast": 18, "clarity": 12, "sharpen": 14,
                     "split_shadow": [180, 130, 70], "split_shadow_amount": 20,
                     "split_highlight": [190, 210, 235], "split_highlight_amount": 14}},
    {"id": "split-decision", "name": "SPLIT DECISION", "category": "Clean + Corrective",
     "description": "Steep contrast, cool blue shadows against warm highlights, vibrance up.",
     "adjustments": {"contrast": 22, "vibrance": 24, "split_shadow": [70, 120, 180],
                     "split_shadow_amount": 24, "split_highlight": [255, 210, 160],
                     "split_highlight_amount": 18, "curve": [[0, 4], [64, 50], [190, 210], [255, 252]]}},
    {"id": "flat-white", "name": "FLAT WHITE", "category": "Portrait",
     "description": "Raised black point and muted greens for a creamy, calm skin balance.",
     "adjustments": {"blacks": 12, "contrast": -8, "temperature": 6, "texture": -6,
                     "col_sat_green": -20, "col_sat_yellow": -14, "col_sat_red": -12}},
    {"id": "hard-liquor", "name": "HARD LIQUOR", "category": "Experimental",
     "description": "Blown midtones, crushed shadows, warm bias, and saturation with a hangover.",
     "adjustments": {"exposure": .08, "contrast": 30, "blacks": -16, "saturation": 18,
                     "temperature": 8, "curve": [[0, 0], [60, 40], [170, 210], [255, 255]]}},
    {"id": "sunday-supplement", "name": "SUNDAY SUPPLEMENT", "category": "Film + Print",
     "description": "Cross-processed newsprint: warm sepia, weak blues, heavy corners.",
     "adjustments": {"temperature": 18, "photo_filter_color": [225, 165, 80], "photo_filter_density": 24,
                     "saturation": -6, "vignette": -28, "curve_blue": [[0, 20], [255, 225]]}},
    {"id": "handshake-deal", "name": "HANDSHAKE DEAL", "category": "Portrait",
     "description": "Lifted midtones and warmer reds and oranges for honest skin.",
     "adjustments": {"exposure": .08, "clarity": 10, "highlights": -8,
                     "col_sat_red": 14, "col_sat_orange": 16, "col_lum_orange": 8}},
    {"id": "picnic-table", "name": "PICNIC TABLE", "category": "Film + Print",
     "description": "A matte, faded finish — blacks to soft grey and a cool-yellow wash.",
     "adjustments": {"blacks": 18, "contrast": -16, "temperature": -4, "tint": 6,
                     "saturation": -8, "texture": -6, "split_shadow": [150, 150, 135],
                     "split_shadow_amount": 14}},
    {"id": "rooftop-bar", "name": "ROOFTOP BAR", "category": "Clean + Corrective",
     "description": "A gentle lift, yellow casts neutralised, and a warm midtone glow.",
     "adjustments": {"exposure": .08, "tint": -4, "glow_amount": 16, "glow_colour": [255, 235, 200],
                     "glow_size": 60, "vignette": -8}},
    {"id": "wheat-beer", "name": "WHEAT BEER", "category": "Film + Print",
     "description": "Heavy gold saturation, amber shadows, and a dark bordered frame.",
     "adjustments": {"saturation": 14, "contrast": 18, "photo_filter_color": [220, 160, 60],
                     "photo_filter_density": 10, "split_shadow": [160, 120, 50],
                     "split_shadow_amount": 26, "vignette": -22}},
    {"id": "amber-alert", "name": "AMBER ALERT", "category": "Portrait",
     "description": "Warmer temperature with amplified orange and yellow, shadows left alone.",
     "adjustments": {"temperature": 16, "col_sat_orange": 14, "col_sat_yellow": 12,
                     "col_lum_orange": 6, "clarity": 6}},
    {"id": "cold-front", "name": "COLD FRONT", "category": "Landscape + Weather",
     "description": "An icy cyan-blue shift, cool shadows, and a brighter middle.",
     "adjustments": {"temperature": -20, "tint": -6, "contrast": 6, "split_shadow": [90, 130, 180],
                     "split_shadow_amount": 20, "glow_amount": 14, "glow_colour": [212, 226, 240],
                     "glow_size": 58}},
    {"id": "plain-truth", "name": "PLAIN TRUTH", "category": "Black + White",
     "description": "Straight monochrome, balanced contrast, deep blacks, crisp whites.",
     "adjustments": {"black_white": True, "contrast": 20, "blacks": -14, "whites": 10,
                     "curve": [[0, 0], [64, 48], [190, 208], [255, 255]]}},
    {"id": "pop-quiz", "name": "POP QUIZ", "category": "Clean + Corrective",
     "description": "Local contrast with warm subjects popped off cool green-blue backgrounds.",
     "adjustments": {"clarity": 12, "vibrance": 10, "col_sat_red": 16, "col_sat_orange": 12,
                     "col_sat_yellow": 10, "col_sat_green": -12, "col_sat_blue": -10}},
    {"id": "heat-lamp", "name": "HEAT LAMP", "category": "Experimental",
     "description": "An extreme peach-and-amber remap with crushed brown shadows.",
     "adjustments": {"temperature": 30, "tint": 8, "saturation": 8, "photo_filter_color": [240, 150, 60],
                     "photo_filter_density": 30, "split_shadow": [110, 70, 40], "split_shadow_amount": 24}},
    {"id": "field-guide", "name": "FIELD GUIDE", "category": "Landscape + Weather",
     "description": "Muted reds and purples, greens and cyans lifted, a soft open exposure.",
     "adjustments": {"exposure": .10, "contrast": -6, "col_sat_red": -16, "col_sat_purple": -18,
                     "col_sat_magenta": -14, "col_sat_green": 14, "col_sat_aqua": 12, "col_lum_green": 6}},
    {"id": "garage-band", "name": "GARAGE BAND", "category": "Experimental",
     "description": "Toy-camera crunch: hard S-curve, zero-black shadows, hyper colour.",
     "adjustments": {"contrast": 30, "blacks": -24, "saturation": 26, "vibrance": 16, "clarity": 10,
                     "curve": [[0, 0], [64, 36], [190, 220], [255, 255]]}},
    {"id": "blueprint", "name": "BLUEPRINT", "category": "Clean + Corrective",
     "description": "Muted colour, hard clarity and micro-texture, a warm highlight cast.",
     "adjustments": {"saturation": -10, "contrast": 8, "clarity": 18, "texture": 12,
                     "split_highlight": [255, 220, 170], "split_highlight_amount": 12}},
    {"id": "swamp-king", "name": "SWAMP KING", "category": "Film + Print",
     "description": "Deep shadows dyed olive, contrast held, highlights kept clean.",
     "adjustments": {"blacks": -18, "contrast": 14, "whites": 8, "split_shadow": [95, 105, 60],
                     "split_shadow_amount": 22}},
    {"id": "blush-response", "name": "BLUSH RESPONSE", "category": "Portrait",
     "description": "A pink-white centre spotlight, gentle midtone contrast, soft edges.",
     "adjustments": {"contrast": 10, "glow_amount": 22, "glow_colour": [255, 220, 225],
                     "glow_size": 50, "vignette": -12}},
    {"id": "silver-gelatin", "name": "SILVER GELATIN", "category": "Black + White",
     "description": "Low-contrast grayscale with charcoal-lifted shadows and smooth highlights.",
     "adjustments": {"black_white": True, "contrast": -8, "blacks": 16, "highlights": -10}},
    {"id": "honky-tonk", "name": "HONKY TONK", "category": "Film + Print",
     "description": "A '70s pastel: magenta shadows, pale-yellow midtones, lifted darks.",
     "adjustments": {"blacks": 16, "contrast": -12, "temperature": 6, "split_shadow": [180, 110, 150],
                     "split_shadow_amount": 20, "split_highlight": [240, 225, 160],
                     "split_highlight_amount": 16}},
    {"id": "sea-glass", "name": "SEA GLASS", "category": "Landscape + Weather",
     "description": "Green and blue luminance up, warm tones pulled back, clean daylight.",
     "adjustments": {"temperature": -6, "contrast": 4, "col_lum_green": 12, "col_lum_blue": 10,
                     "col_sat_red": -12, "col_sat_orange": -10}},
    {"id": "dust-bowl", "name": "DUST BOWL", "category": "Film + Print",
     "description": "Flattened range, washed colour, and darks lifted to a warm dusty grey.",
     "adjustments": {"contrast": -18, "saturation": -22, "blacks": 18, "temperature": 8,
                     "split_shadow": [150, 140, 125], "split_shadow_amount": 16}},
    {"id": "slow-sunrise", "name": "SLOW SUNRISE", "category": "Landscape + Weather",
     "description": "Shadows and midtones opened under a soft amber morning haze.",
     "adjustments": {"exposure": .14, "blacks": 10, "clarity": -5, "split_highlight": [255, 215, 150],
                     "split_highlight_amount": 18, "glow_amount": 18, "glow_colour": [255, 226, 176],
                     "glow_size": 62}},
    {"id": "foothills", "name": "FOOTHILLS", "category": "Landscape + Weather",
     "description": "Soft contrast, lifted blacks, a warm yellow-brown wash, gentle edges.",
     "adjustments": {"contrast": -14, "blacks": 14, "photo_filter_color": [210, 170, 110],
                     "photo_filter_density": 18, "vignette": -12}},
    {"id": "city-limits", "name": "CITY LIMITS", "category": "Landscape + Weather",
     "description": "Brighter midtones, sharpened edges, and even saturation across the frame.",
     "adjustments": {"exposure": .06, "clarity": 14, "sharpen": 12, "saturation": 12, "vibrance": 8}},
    {"id": "snooze-button", "name": "SNOOZE BUTTON", "category": "Film + Print",
     "description": "Desaturated and hazy, blacks lifted, midtones nudged yellow-green.",
     "adjustments": {"saturation": -20, "contrast": -10, "blacks": 16, "tint": 6,
                     "split_shadow": [140, 145, 120], "split_shadow_amount": 14}},
    {"id": "sun-bleached", "name": "SUN BLEACHED", "category": "Landscape + Weather",
     "description": "A bright low-contrast wash with faded highlights and lifted shadows.",
     "adjustments": {"exposure": .10, "contrast": -14, "highlights": -8, "blacks": 14,
                     "saturation": -10}},
    {"id": "last-call", "name": "LAST CALL", "category": "Night + Neon",
     "description": "Lowered light, bruised plum shadows, and a heavy dark surround.",
     "adjustments": {"exposure": -.14, "saturation": -12, "split_shadow": [95, 60, 85],
                     "split_shadow_amount": 24, "vignette": -30}},
    {"id": "space-heater", "name": "SPACE HEATER", "category": "Night + Neon",
     "description": "A fiery orange centre glow, dark magenta shadows, crushed corners.",
     "adjustments": {"glow_amount": 26, "glow_colour": [255, 140, 80], "glow_size": 52,
                     "split_shadow": [110, 60, 90], "split_shadow_amount": 20, "vignette": -28}},
    {"id": "antique-mall", "name": "ANTIQUE MALL", "category": "Film + Print",
     "description": "A warm antique-yellow wash over a lifted, low-contrast curve.",
     "adjustments": {"blacks": 12, "contrast": -10, "highlights": -8,
                     "photo_filter_color": [235, 205, 140], "photo_filter_density": 20}},
    {"id": "nightcap", "name": "NIGHTCAP", "category": "Portrait",
     "description": "A soft peach over the midtones, lifted shadows, and smoothed skin.",
     "adjustments": {"blacks": 12, "contrast": -6, "texture": -8, "split_midtone": [240, 190, 170],
                     "split_midtone_amount": 16}},
    {"id": "pond-hockey", "name": "POND HOCKEY", "category": "Landscape + Weather",
     "description": "Brighter midtones under an ice-blue tint and a soft white centre.",
     "adjustments": {"exposure": .08, "temperature": -14, "tint": -6, "glow_amount": 18,
                     "glow_colour": [235, 240, 245], "glow_size": 60,
                     "split_highlight": [200, 225, 235], "split_highlight_amount": 12}},
    {"id": "soft-focus-sunday", "name": "SOFT FOCUS SUNDAY", "category": "Black + White",
     "description": "A low-contrast monochrome that never hits true black, warmed to cream.",
     "adjustments": {"black_white": True, "contrast": -10, "blacks": 14,
                     "photo_filter_color": [235, 220, 190], "photo_filter_density": 20}},
    {"id": "cross-examined", "name": "CROSS EXAMINED", "category": "Experimental",
     "description": "Cross-process punch: hard S-curve, high colour, teal shadows, dark edges.",
     "adjustments": {"contrast": 30, "saturation": 22, "split_shadow": [50, 110, 110],
                     "split_shadow_amount": 24, "vignette": -30,
                     "curve": [[0, 0], [64, 38], [190, 218], [255, 255]]}},
)


def all_lewks():
    return copy.deepcopy(list(LEWKS))


def get(lewk_id):
    return next((copy.deepcopy(item) for item in LEWKS if item["id"] == lewk_id), None)


def recipe(lewk_id, strength=100):
    """Return a v1 recipe with the complete LEWK blended as one adjustment layer."""
    lewk = get(lewk_id)
    if lewk is None:
        raise KeyError(f"Unknown built-in LEWK: {lewk_id}")
    amount = max(0.0, min(1.0, float(strength) / 100.0))
    values = copy.deepcopy(DEFAULT_ADJUSTMENTS)
    values.update(copy.deepcopy(lewk["adjustments"]))
    provenance = {"id": lewk["id"], "name": lewk["name"],
                  "strength": int(amount * 100), "provenance": "built-in"}
    layer = {"id": str(time.time_ns()), "name": "LEWK · " + lewk["name"],
             "type": "adjustment", "visible": True, "opacity": amount,
             "blend": "normal", "adjustments": values, "mask": "", "styles": {},
             "lewk": copy.deepcopy(provenance)}
    layers = [layer]
    for texture in copy.deepcopy(lewk.get("textures", [])):
        ref = texture.get("asset_ref") or texture
        layers.append({
            "id": str(time.time_ns()), "name": texture.get("name") or ref.get("name") or "Texture",
            "type": "image", "visible": True,
            "opacity": max(0.0, min(1.0, float(texture.get("opacity", 1.0)) * amount)),
            "blend": texture.get("blend", "overlay"), "fit": texture.get("fit", "cover"),
            "path": "", "asset_ref": ref, "adjustments": copy.deepcopy(DEFAULT_ADJUSTMENTS),
            "mask": "", "mask_enabled": True, "mask_linked": True,
            "transform": {}, "styles": {}, "lewk": copy.deepcopy(provenance),
        })
    return {"version": PROJECT_VERSION,
            "adjustments": copy.deepcopy(DEFAULT_ADJUSTMENTS),
            "layers": layers, "lewk": provenance}

# ===== SNAPSMACK EOF =====
