<?php
/**
 * SNAPSMACK — Asset Library Inventory generator.
 *
 * Scans the shared asset library (assets/js, assets/fonts, assets/css) and writes
 * a catalogue of everything a skin developer — or the OH SNAP skin-builder AI —
 * can draw on, WITH a description of what each thing is and what it is for.
 *
 * Descriptions are read from each file's own top-of-file comment (its "purpose"
 * line), so the catalogue stays current as engines change — re-run this after
 * adding or editing an asset. Files whose header carries no description are listed
 * as NEEDS-DESCRIPTION so the gap is visible, not hidden.
 *
 * Two outputs from one pass:
 *   assets/ASSET-INVENTORY.json  — machine-readable, for the OH SNAP AI to load.
 *   assets/ASSET-INVENTORY.md    — plain-English, for skin developers to read.
 *
 * Run:  php tools/asset-inventory.php
 *
 * SNAPSMACK_EOF_HEADER
 *     <?php // ===== SNAPSMACK EOF =====
 * Last non-empty line of this file MUST match the line above.
 */

$root      = dirname(__DIR__);
$js_dir    = $root . '/assets/js';
$css_dir   = $root . '/assets/css';
$fonts_dir = $root . '/assets/fonts';

/** Pull the human "purpose" out of a file's leading comment block. */
function inv_describe(string $path): array {
    $raw = (string) @file_get_contents($path, false, null, 0, 2000);
    if ($raw === '') return ['vendor' => false, 'desc' => ''];

    // Third-party minified libraries announce themselves with /*! ... !*/.
    $vendor = (bool) preg_match('/\.min\.js$/', $path) || str_starts_with(ltrim($raw), '/*!');

    $text = '';
    if (preg_match('~/\*(.*?)\*/~s', $raw, $m)) {          // /* ... */ block
        $text = $m[1];
    } elseif (preg_match('~^(?:\s*//.*\n)+~m', $raw, $m)) {  // // line run
        $text = preg_replace('~^\s*//~m', '', $m[0]);
    }
    // Tidy: drop comment stars, the EOF header boilerplate, collapse whitespace.
    $text = preg_replace('~SNAPSMACK_EOF_HEADER.*$~s', '', $text);
    $text = preg_replace('~^[\s*!]+~m', '', $text);
    $text = trim(preg_replace('~\s+~', ' ', $text));
    $text = preg_replace('~^SNAPSMACK\s*[-–—:]\s*~i', '', $text);
    // Drop a redundant filename echo and any leading emoji/punctuation bytes.
    $base = basename($path);
    if ($base !== '') $text = trim(str_replace($base, '', $text));
    while ($text !== '' && !ctype_alnum($text[0])) $text = substr($text, 1);
    $text = trim(preg_replace('~\s+~', ' ', $text));

    // First sentence / first ~200 chars is the purpose.
    if ($text !== '' && preg_match('~^(.{20,200}?[.!])\s~s', $text . ' ', $mm)) {
        $text = $mm[1];
    } elseif (strlen($text) > 200) {
        $text = substr($text, 0, 197) . '...';
    }
    return ['vendor' => $vendor, 'desc' => $text];
}

/** Which family/role a JS file belongs to, for grouping. */
function inv_js_family(string $name): string {
    if (preg_match('/\.min\.js$/', $name))       return 'Third-party libraries';
    if (str_starts_with($name, 'ss-engine-'))    return 'Skin engines (ss-engine-*) — public-facing behaviour a skin can switch on';
    if (str_starts_with($name, 'smack-'))        return 'Admin & tool scripts (smack-*) — the CMS back office';
    if (str_starts_with($name, 'ss-'))           return 'Shared front-end helpers (ss-*)';
    return 'Other';
}

$catalog = ['generated_note' => 'Auto-generated by tools/asset-inventory.php from each asset\'s own header. Re-run after adding/editing assets.', 'javascript' => [], 'fonts' => [], 'css' => []];

// --- JavaScript ---
foreach (glob($js_dir . '/*.js') ?: [] as $f) {
    if (str_ends_with($f, '.bak')) continue;
    $name = basename($f);
    $d = inv_describe($f);
    $catalog['javascript'][] = [
        'file'    => 'assets/js/' . $name,
        'enable'  => str_starts_with($name, 'ss-engine-') ? 'declare in the skin manifest require_scripts, or it loads via core/footer-scripts.php' : 'loaded by the CMS where needed',
        'family'  => inv_js_family($name),
        'vendor'  => $d['vendor'],
        'purpose' => $d['desc'] !== '' ? $d['desc'] : 'NEEDS-DESCRIPTION (no purpose line in the file header)',
    ];
}

// --- Fonts ---
foreach (glob($fonts_dir . '/*', GLOB_ONLYDIR) ?: [] as $d) {
    $fam  = basename($d);
    $files = array_map('basename', glob($d . '/*.{ttf,otf,woff,woff2}', GLOB_BRACE) ?: []);
    $lic  = glob($d . '/*{LICENSE,license,OFL,ofl}*', GLOB_BRACE) ?: [];
    $catalog['fonts'][] = [
        'family'  => $fam,
        'dir'     => 'assets/fonts/' . $fam,
        'files'   => $files,
        'license' => $lic ? basename($lic[0]) : 'NEEDS-CHECK (no licence file in the folder)',
        'purpose' => 'Display/branding typeface. Skins reference it by family name in @font-face / CSS.',
    ];
}

// --- CSS ---
foreach (glob($css_dir . '/*.css') ?: [] as $f) {
    if (str_ends_with($f, '.bak')) continue;
    $name = basename($f);
    $d = inv_describe($f);
    $catalog['css'][] = [
        'file'    => 'assets/css/' . $name,
        'purpose' => $d['desc'] !== '' ? $d['desc'] : 'NEEDS-DESCRIPTION (no purpose line in the file header)',
    ];
}

// --- Write JSON (for the OH SNAP AI) ---
@file_put_contents($root . '/assets/ASSET-INVENTORY.json',
    json_encode($catalog, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");

// --- Write Markdown (for skin developers) ---
$md  = "# SnapSmack Asset Library — Inventory\n\n";
$md .= "> Auto-generated by `tools/asset-inventory.php` from each asset's own header. **Re-run it after adding or editing an asset.** Anything marked NEEDS-DESCRIPTION has no purpose line in its file header yet — add one and re-run.\n\n";

$js_by_family = [];
foreach ($catalog['javascript'] as $e) $js_by_family[$e['family']][] = $e;
$md .= "## JavaScript (" . count($catalog['javascript']) . " files)\n\n";
foreach ($js_by_family as $family => $items) {
    $md .= "### {$family}\n\n";
    foreach ($items as $e) {
        $md .= "- **`" . basename($e['file']) . "`** — {$e['purpose']}\n";
    }
    $md .= "\n";
}
$md .= "## Fonts (" . count($catalog['fonts']) . " families)\n\n";
foreach ($catalog['fonts'] as $e) {
    $md .= "- **{$e['family']}** — {$e['purpose']} (licence: {$e['license']})\n";
}
$md .= "\n## Shared CSS (" . count($catalog['css']) . " files)\n\n";
foreach ($catalog['css'] as $e) {
    $md .= "- **`" . basename($e['file']) . "`** — {$e['purpose']}\n";
}
$md .= "\n<!-- generated; edit the source assets' headers, not this file -->\n";
@file_put_contents($root . '/assets/ASSET-INVENTORY.md', $md);

$needs = 0;
foreach ($catalog['javascript'] as $e) if (str_starts_with($e['purpose'], 'NEEDS')) $needs++;
foreach ($catalog['css'] as $e)        if (str_starts_with($e['purpose'], 'NEEDS')) $needs++;
echo "Asset inventory written:\n  assets/ASSET-INVENTORY.json\n  assets/ASSET-INVENTORY.md\n";
echo "JS: " . count($catalog['javascript']) . " · Fonts: " . count($catalog['fonts']) . " · CSS: " . count($catalog['css']) . "\n";
echo "Entries still needing a description in their header: {$needs}\n";
// ===== SNAPSMACK EOF =====
