<?php
/**
 * SNAPSMACK - Full Install Package Builder
 * Alpha v0.7.3
 *
 * Builds a complete clean install zip for distribution on snapsmack.ca/releases.
 * Unlike build-release.php (which creates delta packages between git tags),
 * this script packages the entire codebase into a fresh install zip.
 *
 * The package is what a new user downloads, extracts to their web root, and
 * hits install.php to set up. It excludes dev files, .git, user data dirs,
 * and anything that would only exist on a live install.
 *
 * USAGE:
 *   php build-install-package.php
 *   php build-install-package.php --output ./releases/
 *   php build-install-package.php --output ./releases/ --sign
 *
 * REQUIREMENTS:
 *   - Run from within the SnapSmack git repository
 *   - PHP 8.0+ with ZipArchive
 */

if (php_sapi_name() !== 'cli') {
    die("This tool must be run from the command line.\n");
}

// ─── PATHS ──────────────────────────────────────────────────────────────────

$project_root = dirname(__DIR__);

// ─── ARGUMENT PARSING ───────────────────────────────────────────────────────

$args = parse_args($argv);
$output_dir = $args['output'] ?? $project_root;
$do_sign = $args['sign'] ?? false;

if (!is_dir($output_dir)) {
    mkdir($output_dir, 0755, true);
}

// ─── READ VERSION ───────────────────────────────────────────────────────────

$constants_file = $project_root . '/core/constants.php';
if (!file_exists($constants_file)) {
    die("ERROR: core/constants.php not found. Run from the SnapSmack project root.\n");
}

$constants_content = file_get_contents($constants_file);
preg_match("/SNAPSMACK_VERSION',\s*'([^']+)'/", $constants_content, $m_full);
preg_match("/SNAPSMACK_VERSION_SHORT',\s*'([^']+)'/", $constants_content, $m_short);
preg_match("/SNAPSMACK_VERSION_CODENAME',\s*'([^']+)'/", $constants_content, $m_codename);

$version_full  = $m_full[1]  ?? 'Unknown';
$version_short = $m_short[1] ?? '0.0';
$version_codename = $m_codename[1] ?? '';

echo "SNAPSMACK INSTALL PACKAGE BUILDER\n";
echo "──────────────────────────────────\n";
$version_display = $version_codename ? "{$version_full} \"{$version_codename}\"" : $version_full;
echo "  Version:  {$version_display} (v{$version_short})\n";
echo "  Source:   {$project_root}\n";
echo "  Output:   {$output_dir}\n\n";

// ─── EXCLUSION RULES ────────────────────────────────────────────────────────

// Directories to skip entirely (relative to project root)
$exclude_dirs = [
    '.git',
    '.well-known',
    'backups',
    'cgi-bin',
    'database',
    'docs',
    'img_uploads',         // Created by installer
    'media_assets',        // Created by installer
    'node_modules',
    'public',
    'screenshots',
    'tools',               // Dev-only tools
    'skins/kiosk',              // Development status — not ready for distribution
    'skins/the-grid',           // Development status — not ready for distribution
    'skins/impact-printer',     // Specialty skin — available via skin gallery
    'skins/true-grit',          // 20MB+ textures — available via skin gallery
    'skins/a-grey-reckoning',   // Development skin — not for distribution
    'skins/50-shades-of-noah-grey', // Derivative of a-grey-reckoning — not for distribution
];

// Individual files to skip
$exclude_files = [
    '.gitignore',
    'CLAUDE.md',
    'core/db.php',         // Generated by installer
    'core/constants.php',  // Generated by installer (version stamped)
    'skin-picker-reference.docx',
    'the-grid-design-document.docx',
];

// File patterns to skip
$exclude_patterns = [
    '/\.docx$/',
    '/\.sql$/',            // DB dumps
];

// ─── BUILD FILE LIST ────────────────────────────────────────────────────────

echo "Scanning files...\n";

$files_to_include = [];
$files_skipped = 0;

$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($project_root, RecursiveDirectoryIterator::SKIP_DOTS),
    RecursiveIteratorIterator::SELF_FIRST
);

foreach ($iterator as $file) {
    $real = $file->getRealPath();
    $relative = str_replace($project_root . DIRECTORY_SEPARATOR, '', $real);
    $relative = str_replace('\\', '/', $relative);

    // Skip excluded directories
    $skip = false;
    foreach ($exclude_dirs as $excl) {
        if (str_starts_with($relative, $excl . '/') || $relative === $excl) {
            $skip = true;
            break;
        }
    }
    if ($skip) { $files_skipped++; continue; }

    // Skip excluded files
    if (in_array($relative, $exclude_files)) {
        $files_skipped++;
        continue;
    }

    // Skip patterns
    foreach ($exclude_patterns as $pat) {
        if (preg_match($pat, $relative)) {
            $skip = true;
            break;
        }
    }
    if ($skip) { $files_skipped++; continue; }

    // Only include actual files
    if ($file->isFile()) {
        $files_to_include[] = $relative;
    }
}

// Always include the template constants.php (we'll generate a clean one)
// and an empty db.php placeholder
$include_generated = true;

sort($files_to_include);

echo "  Found " . count($files_to_include) . " files to package\n";
echo "  Skipped {$files_skipped} excluded entries\n\n";

// ─── BUILD ZIP ──────────────────────────────────────────────────────────────

$safe_ver = preg_replace('/[^a-zA-Z0-9._-]/', '', $version_short);
$zip_name = "snapsmack-{$safe_ver}.zip";
$zip_path = rtrim($output_dir, '/') . '/' . $zip_name;
$wrapper  = "snapsmack-{$safe_ver}/";

echo "Building {$zip_name}...\n";

$zip = new ZipArchive();
if ($zip->open($zip_path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
    die("ERROR: Could not create {$zip_path}\n");
}

$file_count = 0;

foreach ($files_to_include as $relative) {
    $full_path = $project_root . '/' . $relative;
    if (!file_exists($full_path)) continue;

    $zip->addFile($full_path, $wrapper . $relative);
    $file_count++;
}

// Add generated files
if ($include_generated) {
    // Clean constants.php with version info
    $constants_template = <<<'PHP'
<?php
/**
 * SNAPSMACK - System Constants
 * %%VERSION_FULL%%
 *
 * Defines version strings and system-wide constants. This file is generated
 * by the installer and updated by the self-update system.
 */

define('SNAPSMACK_VERSION', '%%VERSION_FULL%%');
define('SNAPSMACK_VERSION_SHORT', '%%VERSION_SHORT%%');
define('SNAPSMACK_VERSION_CODENAME', '%%VERSION_CODENAME%%');

// --- MOBILE SKIN OVERRIDE ---
define('SNAPSMACK_MOBILE_SKIN', 'photogram');

/**
 * Detect mobile devices via User-Agent string.
 */
function snapsmack_is_mobile(): bool {
    $ua = $_SERVER['HTTP_USER_AGENT'] ?? '';
    if (empty($ua)) return false;
    return (bool) preg_match('/Mobile|iPhone|iPod|Android.*Mobile|webOS|BlackBerry|Opera Mini|IEMobile|Windows Phone/i', $ua);
}
PHP;
    $constants_template = str_replace('%%VERSION_FULL%%', $version_full, $constants_template);
    $constants_template = str_replace('%%VERSION_SHORT%%', $version_short, $constants_template);
    $constants_template = str_replace('%%VERSION_CODENAME%%', $version_codename, $constants_template);
    $zip->addFromString($wrapper . 'core/constants.php', $constants_template);
    $file_count++;

    // Empty placeholder directories (zip needs at least one file in each)
    $zip->addFromString($wrapper . 'img_uploads/.gitkeep', '');
    $zip->addFromString($wrapper . 'media_assets/.gitkeep', '');
    $zip->addFromString($wrapper . 'backups/.gitkeep', '');
    $file_count += 3;
}

$zip->close();

$checksum = hash_file('sha256', $zip_path);
$filesize = filesize($zip_path);

echo "\n  Package:  {$zip_name}\n";
echo "  Files:    {$file_count}\n";
echo "  Size:     " . number_format($filesize) . " bytes (" . round($filesize / 1048576, 2) . " MB)\n";
echo "  SHA-256:  {$checksum}\n";

// ─── GENERATE LATEST.JSON ───────────────────────────────────────────────────

$json_path = rtrim($output_dir, '/') . '/latest.json';
$download_url = "https://snapsmack.ca/releases/{$zip_name}";

$manifest = [
    'version'         => $version_short,
    'version_full'    => $version_full,
    'codename'        => $version_codename,
    'released'        => date('Y-m-d'),
    'download_url'    => $download_url,
    'checksum_sha256' => $checksum,
    'signature'       => '',
    'download_size'   => $filesize,
    'requires_php'    => '8.0',
    'requires_mysql'  => '5.7',
    'schema_changes'  => false,
    'changelog'       => ['Initial public release'],
    'file_changes'    => [
        'added'    => [],
        'modified' => [],
        'removed'  => [],
    ],
];

file_put_contents($json_path, json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
echo "\n  Manifest: latest.json\n";

// ─── NEXT STEPS ─────────────────────────────────────────────────────────────

echo "\n";
echo "NEXT STEPS\n";
echo "══════════\n";

if ($do_sign) {
    echo "  Signing requested — run:\n";
    echo "  php tools/sign-release.php {$zip_path} --version {$version_short}\n\n";
} else {
    echo "  1. Sign the package:\n";
    echo "     php tools/sign-release.php {$zip_name} --version {$version_short}\n\n";
}

echo "  2. Update the signature in latest.json\n";
echo "  3. Upload {$zip_name} to https://snapsmack.ca/releases/\n";
echo "  4. Upload latest.json to https://snapsmack.ca/releases/\n";
echo "  5. Test: download the zip and run install.php\n\n";

echo "Done.\n";

exit(0);


// ─── HELPERS ────────────────────────────────────────────────────────────────

function parse_args(array $argv): array {
    $result = ['output' => null, 'sign' => false];

    $skip_next = false;
    for ($i = 1; $i < count($argv); $i++) {
        if ($skip_next) { $skip_next = false; continue; }

        $arg = $argv[$i];

        if ($arg === '--output' && isset($argv[$i + 1])) {
            $result['output'] = $argv[$i + 1];
            $skip_next = true;
        } elseif ($arg === '--sign') {
            $result['sign'] = true;
        } elseif ($arg === '--help' || $arg === '-h') {
            echo "SNAPSMACK INSTALL PACKAGE BUILDER\n";
            echo "─────────────────────────────────\n\n";
            echo "Packages the entire SnapSmack codebase into a clean install zip.\n\n";
            echo "Usage:\n";
            echo "  php build-install-package.php [--output DIR] [--sign]\n\n";
            echo "Options:\n";
            echo "  --output DIR   Output directory (default: project root)\n";
            echo "  --sign         Reminder to sign after building\n\n";
            echo "Examples:\n";
            echo "  php build-install-package.php\n";
            echo "  php build-install-package.php --output ./releases/\n\n";
            exit(0);
        }
    }

    return $result;
}
