#!/usr/bin/env python3
# SNAPSMACK_EOF_HEADER — last non-empty line of this file MUST be the .py EOF
# marker: a hash comment with five '=', space, SNAPSMACK EOF, space, five '='.
"""
Bump the PATCH component of BUILD_VERSION in main.py (0.1.X -> 0.1.X+1).

Patch only, always. 0.1.16 is followed by 0.1.17 and never by 0.2.0 — a minor
bump is a decision somebody makes on purpose, not something a build script does
because the number looked big enough.

Run automatically by build.bat before each PyInstaller build, so no exe ever
ships with a version already on somebody's disk. Also regenerates
version_info.txt, which stamps the version into the Windows file properties;
without that the exe shows no version at all no matter what BUILD_VERSION says.
"""
import re
import sys
from pathlib import Path

MAIN = Path(__file__).with_name("main.py")
VERSION_INFO = Path(__file__).with_name("version_info.txt")


def _write_version_info(minor: int, patch: int) -> None:
    ver = f"0.{minor}.{patch}"
    VERSION_INFO.write_text(f'''# Auto-generated by bump_version.py - do not edit. Regenerated every build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(0, {minor}, {patch}, 0),
    prodvers=(0, {minor}, {patch}, 0),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'SnapSmack'),
        StringStruct('FileDescription', 'TAKE YOUR SHIT WITH YOU - portable export for SnapSmack'),
        StringStruct('FileVersion', '{ver}'),
        StringStruct('InternalName', 'tyswy'),
        StringStruct('LegalCopyright', 'SnapSmack'),
        StringStruct('OriginalFilename', 'tyswy.exe'),
        StringStruct('ProductName', 'TAKE YOUR SHIT WITH YOU'),
        StringStruct('ProductVersion', '{ver}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
''', encoding="utf-8")


def main() -> int:
    if not MAIN.exists():
        print("bump_version: main.py not found", file=sys.stderr)
        return 1
    src = MAIN.read_text(encoding="utf-8")
    m = re.search(r'^BUILD_VERSION\s*=\s*"0\.(\d+)\.(\d+)"', src, re.M)
    if not m:
        print("bump_version: BUILD_VERSION not found in main.py", file=sys.stderr)
        return 1
    minor, patch = int(m.group(1)), int(m.group(2)) + 1
    src = src[:m.start()] + f'BUILD_VERSION = "0.{minor}.{patch}"' + src[m.end():]
    MAIN.write_text(src, encoding="utf-8")
    _write_version_info(minor, patch)
    print(f"bump_version: BUILD_VERSION -> 0.{minor}.{patch}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# ===== SNAPSMACK EOF =====
