#!/usr/bin/env python3
# SNAPSMACK_EOF_HEADER — last non-empty line of this file MUST be the .py EOF
# marker: a hash comment with five '=', space, SNAPSMACK EOF, space, five '='.
"""
Bump the patch component of BUILD_VERSION in main.py (0.7.X -> 0.7.X+1).

Run automatically by build.bat before each PyInstaller build, so every exe is
stamped with a fresh, auto-incrementing 0.7.xx version — matching the 0.7.x
scheme used by the SnapSmack CMS and the unzucker tool.
"""
import re
import sys
from pathlib import Path

MAIN = Path(__file__).with_name("main.py")
VERSION_INFO = Path(__file__).with_name("version_info.txt")


def _write_version_info(patch: int) -> None:
    """Emit the PyInstaller Windows version resource so the built exe carries the
    version in its file Properties → Details. Regenerated every build; build.bat
    passes it via --version-file. Without this the exe shows NO version no matter
    how high BUILD_VERSION climbs — which is the bug that kept coming back."""
    ver = f"0.7.{patch}"
    VERSION_INFO.write_text(f'''# Auto-generated by bump_version.py — do not edit. Regenerated every build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(0, 7, {patch}, 0),
    prodvers=(0, 7, {patch}, 0),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'SnapSmack'),
        StringStruct('FileDescription', 'FLKR FCKR - Flickr export importer for SnapSmack'),
        StringStruct('FileVersion', '{ver}'),
        StringStruct('InternalName', 'flkrfckr'),
        StringStruct('OriginalFilename', 'flkrfckr.exe'),
        StringStruct('ProductName', 'FLKR FCKR'),
        StringStruct('ProductVersion', '{ver}'),
        StringStruct('LegalCopyright', '(c) Sean McCormick'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
''', encoding="utf-8")


def main() -> int:
    src = MAIN.read_text(encoding="utf-8")
    m = re.search(r'BUILD_VERSION\s*=\s*"0\.7\.(\d+)"', src)
    if not m:
        print('bump_version: BUILD_VERSION = "0.7.N" not found in main.py', file=sys.stderr)
        return 1
    new_patch = int(m.group(1)) + 1
    src = re.sub(
        r'(BUILD_VERSION\s*=\s*")0\.7\.\d+(")',
        lambda mm: f'{mm.group(1)}0.7.{new_patch}{mm.group(2)}',
        src, count=1,
    )
    MAIN.write_text(src, encoding="utf-8")
    _write_version_info(new_patch)
    print(f"bump_version: BUILD_VERSION -> 0.7.{new_patch}  (+ version_info.txt written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
# ===== SNAPSMACK EOF =====
