# -*- mode: python ; coding: utf-8 -*-
# FLKR FCKR build recipe — Qt shell (flkrfckr_launcher.py → flkrfckr_qt.py).
# Copied from tools/sybu/sybu.spec: every local .py and every tools/_shared/*.py
# is bundled (data copy + forced hidden import) so a module can never be
# silently dropped from the exe. version_info.txt (regenerated by
# bump_version.py) stamps the Windows file version; assets/icon.ico is the
# app icon — keep both or the exe ships unversioned / iconless.
import os, glob, sys
sys.setrecursionlimit(sys.getrecursionlimit() * 5)

_src = SPECPATH

_py_files   = glob.glob(os.path.join(_src, '*.py'))
_local_data = [(f, '.') for f in _py_files]
_local_mods = [os.path.splitext(os.path.basename(f))[0]
               for f in _py_files
               if os.path.basename(f) not in ('main.py', 'bump_version.py')]

_shared_dir   = os.path.normpath(os.path.join(_src, '..', '_shared'))
_shared_files = glob.glob(os.path.join(_shared_dir, '*.py'))
_shared_data  = [(f, '.') for f in _shared_files]
_shared_mods  = [os.path.splitext(os.path.basename(f))[0] for f in _shared_files]

a = Analysis(
    ['flkrfckr_launcher.py'],
    pathex=[_src, _shared_dir],
    binaries=[],
    datas=_local_data + _shared_data + [(os.path.join(_src, 'assets'), 'assets')],
    hiddenimports=_local_mods + _shared_mods + [
        'PySide6', 'PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets',
        'PIL', 'PIL.Image',
        'requests',
        # credential vault (SECAUDIT 040 finding A) — keyring picks its backend
        # at runtime, so static analysis misses every backend without this.
        'cryptography', 'keyring', 'keyring.backends',
        'keyring.backends.Windows', 'keyring.backends.chainer',
        'keyring.backends.fail', 'keyring.backends.null',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'PIL.ImageTk', 'PIL._tkinter_finder',
        'torch', 'tensorflow', 'scipy', 'sklearn', 'matplotlib', 'pandas',
        'numpy.distutils', 'IPython', 'notebook',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='flkrfckr',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(_src, 'assets', 'icon.ico'),
    version=os.path.join(_src, 'version_info.txt'),
)
# ===== SNAPSMACK EOF =====
